// Code generated by gentity. DO NOT EDIT.

package dto 

import (
	"bytes" 
	"errors" 
	"github.com/linbaozhong/gentity/pkg/gjson" 
	"github.com/linbaozhong/gentity/pkg/log" 
	"github.com/linbaozhong/gentity/pkg/validator" 
	"github.com/linbaozhong/gentity/pkg/types" 
	"github.com/linbaozhong/gentity/pkg/conv" 
	"net/http" 
) 

var _ = conv.Any2String("")
var _ = bytes.NewBuffer(nil)

/*
	--- UserRegisterReq ---
*/
// Init
func (p *UserRegisterReq) Init() error {
	p.UserName = nil
	p.Password = nil
	p.Email = nil

	return nil
}

// Check
func (p *UserRegisterReq) Check() error {
	if p.UserName == nil {
		return types.NewError(http.StatusBadRequest, "user_name is required")
	}
	if p.Password == nil {
		return types.NewError(http.StatusBadRequest, "password is required")
	}
	if p.Email != nil && !validator.IsEmail(*p.Email) {
		return types.NewError(http.StatusBadRequest, "邮箱格式错误")
	}
	return nil
}

// UnmarshalJSON
func (p *UserRegisterReq) UnmarshalJSON(data []byte) error {
	defer func() {
		if r := recover(); r != nil {
			log.Error(r)
			return
		}
	}()

	ok := gjson.ValidBytes(data)
	if !ok {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	var e error
	_result.ForEach(func(key, value gjson.Result) bool {
		switch key.Str {
		case "user_name":
			e = types.Unmarshal(value, &p.UserName, func(value gjson.Result) *string {
				var obj *string
				e := types.Unmarshal(value, &obj)
				if e != nil {
					panic(e)
				}
				return obj
			}(value))
		case "password":
			e = types.Unmarshal(value, &p.Password, func(value gjson.Result) *string {
				var obj *string
				e := types.Unmarshal(value, &obj)
				if e != nil {
					panic(e)
				}
				return obj
			}(value))
		case "email":
			e = types.Unmarshal(value, &p.Email, func(value gjson.Result) *string {
				var obj *string
				e := types.Unmarshal(value, &obj)
				if e != nil {
					panic(e)
				}
				return obj
			}(value))
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// UnmarshalValues
func (p *UserRegisterReq) UnmarshalValues(m map[string][]string) error {
	defer func() {
		if r := recover(); r != nil {
			log.Error(r)
			return
		}
	}()

	var e error
	for k, v := range m {
		value := gjson.Result{Type: gjson.String, Raw: v[0], Str: v[0]}
		switch k {
		case "user_name":
			e = types.Unmarshal(value, &p.UserName, func(value gjson.Result) *string {
				var obj *string
				e := types.Unmarshal(value, &obj)
				if e != nil {
					panic(e)
				}
				return obj
			}(value))
		case "password":
			e = types.Unmarshal(value, &p.Password, func(value gjson.Result) *string {
				var obj *string
				e := types.Unmarshal(value, &obj)
				if e != nil {
					panic(e)
				}
				return obj
			}(value))
		case "email":
			e = types.Unmarshal(value, &p.Email, func(value gjson.Result) *string {
				var obj *string
				e := types.Unmarshal(value, &obj)
				if e != nil {
					panic(e)
				}
				return obj
			}(value))
		}
		if e != nil {
			log.Error(e)
			return e
		}
	}

	return nil
}

/*
	--- UserRegisterResp ---
*/
// MarshalJSON
func (p *UserRegisterResp) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(3 * 50)
	write.WriteRaw("user_id", types.Marshal(p.UserID))
	write.WriteRaw("user_name", types.Marshal(p.UserName))
	if p.Email != "" {
		write.WriteRaw("email", types.Marshal(p.Email))
	}
	return write.Bytes(), nil
}

/*
	--- GetUserReq ---
*/
// Init
func (p *GetUserReq) Init() error {
	p.UserID = nil

	return nil
}

// Check
func (p *GetUserReq) Check() error {
	return nil
}

// UnmarshalJSON
func (p *GetUserReq) UnmarshalJSON(data []byte) error {
	defer func() {
		if r := recover(); r != nil {
			log.Error(r)
			return
		}
	}()

	ok := gjson.ValidBytes(data)
	if !ok {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	var e error
	_result.ForEach(func(key, value gjson.Result) bool {
		switch key.Str {
		case "user_id":
			e = types.Unmarshal(value, &p.UserID, func(value gjson.Result) *uint64 {
				var obj *uint64
				e := types.Unmarshal(value, &obj)
				if e != nil {
					panic(e)
				}
				return obj
			}(value))
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// UnmarshalValues
func (p *GetUserReq) UnmarshalValues(m map[string][]string) error {
	defer func() {
		if r := recover(); r != nil {
			log.Error(r)
			return
		}
	}()

	var e error
	for k, v := range m {
		value := gjson.Result{Type: gjson.String, Raw: v[0], Str: v[0]}
		switch k {
		case "user_id":
			e = types.Unmarshal(value, &p.UserID, func(value gjson.Result) *uint64 {
				var obj *uint64
				e := types.Unmarshal(value, &obj)
				if e != nil {
					panic(e)
				}
				return obj
			}(value))
		}
		if e != nil {
			log.Error(e)
			return e
		}
	}

	return nil
}

/*
	--- GetUserResp ---
*/
// MarshalJSON
func (p *GetUserResp) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(3 * 50)
	write.WriteRaw("user_id", types.Marshal(p.UserID))
	write.WriteRaw("user_name", types.Marshal(p.UserName))
	if p.Email != "" {
		write.WriteRaw("email", types.Marshal(p.Email))
	}
	return write.Bytes(), nil
}
