// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
	"tui/internal/model/define/table/tbluser"
)

var (
	userPool = pool.New[*User](func() any {
		_obj := &User{}
		return _obj
	})
)

func NewUser() *User {
	_obj := userPool.Get()
	return _obj
}

// MarshalJSON
func (p *User) MarshalJSON() ([]byte, error) {
	write := types.NewJsonWriter(11 * 50)
	if p.Id != 0 {
		write.WriteRaw("id", types.Marshal(p.Id))
	}
	if p.Name != "" {
		write.WriteRaw("name", types.Marshal(p.Name))
	}
	if p.Email != "" {
		write.WriteRaw("email", types.Marshal(p.Email))
	}
	if p.Mobile != "" {
		write.WriteRaw("mobile", types.Marshal(p.Mobile))
	}
	if p.Gender != "" {
		write.WriteRaw("gender", types.Marshal(p.Gender))
	}
	if p.Birthday != "" {
		write.WriteRaw("birthday", types.Marshal(p.Birthday))
	}
	if p.Creator != 0 {
		write.WriteRaw("creator", types.Marshal(p.Creator))
	}
	if p.Status != 0 {
		write.WriteRaw("status", types.Marshal(p.Status))
	}
	if p.State != 0 {
		write.WriteRaw("state", types.Marshal(p.State))
	}
	if !p.Ctime.IsZero() {
		write.WriteRaw("ctime", types.Marshal(p.Ctime))
	}
	if !p.Utime.IsZero() {
		write.WriteRaw("utime", types.Marshal(p.Utime))
	}
	return write.Bytes(), nil
}

// UnmarshalJSON
func (p *User) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "name":
			p.Name = types.String(value.Str)
		case "email":
			p.Email = types.String(value.Str)
		case "mobile":
			p.Mobile = types.String(value.Str)
		case "gender":
			p.Gender = types.String(value.Str)
		case "birthday":
			p.Birthday = types.String(value.Str)
		case "creator":
			p.Creator = types.BigInt(value.Uint())
		case "status":
			p.Status = types.Int8(value.Int())
		case "state":
			p.State = types.Int8(value.Int())
		case "ctime":
			p.Ctime = types.Time{Time: value.Time()}
		case "utime":
			p.Utime = types.Time{Time: value.Time()}
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *User) Free() {
	if p == nil {
		return
	}

	userPool.Put(p)
}

// Reset
func (p *User) Reset() {
	p.Id = 0
	p.Name = ""
	p.Email = ""
	p.Mobile = ""
	p.Gender = ""
	p.Birthday = ""
	p.Creator = 0
	p.Status = 0
	p.State = 0
	p.Ctime = types.Time{}
	p.Utime = types.Time{}

}

func (p *User) TableName() string {
	return "user"
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var userFieldToPtrFunc = map[string]func(*User) any{
	tbluser.Id.Name:       func(p *User) any { return &p.Id },
	tbluser.Name.Name:     func(p *User) any { return &p.Name },
	tbluser.Email.Name:    func(p *User) any { return &p.Email },
	tbluser.Mobile.Name:   func(p *User) any { return &p.Mobile },
	tbluser.Gender.Name:   func(p *User) any { return &p.Gender },
	tbluser.Birthday.Name: func(p *User) any { return &p.Birthday },
	tbluser.Creator.Name:  func(p *User) any { return &p.Creator },
	tbluser.Status.Name:   func(p *User) any { return &p.Status },
	tbluser.State.Name:    func(p *User) any { return &p.State },
	tbluser.Ctime.Name:    func(p *User) any { return &p.Ctime },
	tbluser.Utime.Name:    func(p *User) any { return &p.Utime },
}

// fieldPtr 根据字段参数，返回对应的指针获取函数列表（与具体实例无关，可缓存复用）
func (p *User) fieldPtr(args ...dialect.Field) []func(*User) any {
	if len(args) == 0 {
		args = tbluser.ReadableFields
	}
	fs := make([]func(*User) any, 0, len(args))
	for _, col := range args {
		if f, ok := userFieldToPtrFunc[col.Name]; ok {
			fs = append(fs, f)
		}
	}
	return fs
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *User) AssignPtr(args ...dialect.Field) []any {
	fs := p.fieldPtr(args...)
	_vals := make([]any, len(fs))
	for i, f := range fs {
		_vals[i] = f(p)
	}
	return _vals
}

// AssignPtrByColumns 根据 SQL 实际返回的列名，按列顺序返回对应字段的指针切片。
// 列在映射表中找不到对应字段时，用一个占位指针跳过（保持列数/顺序与 rows 一致），避免 Scan 报错。
// 参数 cols 为 rows.Columns() 返回的列名切片。
func (p *User) AssignPtrByColumns(cols ...string) []any {
	_vals := make([]any, 0, len(cols))
	for _, col := range cols {
		if ptrFunc, ok := userFieldToPtrFunc[col]; ok {
			_vals = append(_vals, ptrFunc(p))
			continue
		}
		// 列名在结构体中找不到对应字段：用忽略指针占位，保证列数对齐
		var ignore any
		_vals = append(_vals, &ignore)
	}
	return _vals
}

func (p *User) Slice(rows *sql.Rows, args ...dialect.Field) ([]*User, bool, error) {
	defer rows.Close()
	users := make([]*User, 0)

	// 只获取一次：字段 -> ptrFunc 的有序列表（与实例无关）
	fs := p.fieldPtr(args...)

	// 复用的扫描目标切片，循环外分配一次
	_vals := make([]any, len(fs))

	for rows.Next() {
		_p := NewUser()
		// 每行只做"指针绑定到新实例"，
		for i, f := range fs {
			_vals[i] = f(_p)
		}

		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		users = append(users, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return users, len(users) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *User) RawAssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tbluser.WritableFields
	}
	return p.AssignValues(d, args...)
}

// 定义字段到值检查和获取函数的映射
var userFieldToValueFunc = map[dialect.Field]func(*User) (any, bool){
	tbluser.Id: func(p *User) (any, bool) {
		return p.Id, p.Id == 0
	},
	tbluser.Name: func(p *User) (any, bool) {
		return p.Name, p.Name == ""
	},
	tbluser.Email: func(p *User) (any, bool) {
		return p.Email, p.Email == ""
	},
	tbluser.Mobile: func(p *User) (any, bool) {
		return p.Mobile, p.Mobile == ""
	},
	tbluser.Gender: func(p *User) (any, bool) {
		return p.Gender, p.Gender == ""
	},
	tbluser.Birthday: func(p *User) (any, bool) {
		return p.Birthday, p.Birthday == ""
	},
	tbluser.Creator: func(p *User) (any, bool) {
		return p.Creator, p.Creator == 0
	},
	tbluser.Status: func(p *User) (any, bool) {
		return p.Status, p.Status == 0
	},
	tbluser.State: func(p *User) (any, bool) {
		return p.State, p.State == 0
	},
	tbluser.Ctime: func(p *User) (any, bool) {
		return p.Ctime, p.Ctime.IsZero()
	},
	tbluser.Utime: func(p *User) (any, bool) {
		return p.Utime, p.Utime.IsZero()
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *User) AssignValues(d dialect.Dialect, args ...dialect.Field) ([]string, []any) {
	// 未传参时使用全部可写字段，并跳过零值
	skipZero := len(args) == 0
	if skipZero {
		args = tbluser.WritableFields
	}

	cols := make([]string, 0, len(args))
	vals := make([]any, 0, len(args))

	for _, arg := range args {
		if valueFunc, exists := userFieldToValueFunc[arg]; exists {
			value, isZero := valueFunc(p)
			// 显式指定字段时全量包含；默认模式跳过零值字段
			if skipZero && isZero {
				continue
			}
			cols = append(cols, arg.Quote(d))
			vals = append(vals, value)
		}
	}
	return cols, vals
}

func (p *User) AssignKeys() (dialect.Field, any) {
	return tbluser.PrimaryKey, p.Id
}

func (p *User) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
