// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package db

import (
	"database/sql"
	"github.com/linbaozhong/gentity/example/model/define/table/tblcompany"
	"github.com/linbaozhong/gentity/pkg/ace"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"time"
)

const CompanyTableName = "company"

var (
	companyPool = pool.New(ace.Context, func() any {
		obj := &Company{}
		obj.UUID()
		return obj
	})
)

func NewCompany() *Company {
	obj := companyPool.Get().(*Company)
	return obj
}

// Free
func (p *Company) Free() {
	if p == nil {
		return
	}

	companyPool.Put(p)
}

// Reset
func (p *Company) Reset() {
	p.Id = 0
	p.Platform = ""
	p.CorpId = ""
	p.CorpType = 0
	p.FullCorpName = ""
	p.CorpType2 = 0
	p.CorpName = ""
	p.Industry = ""
	p.IsAuthenticated = false
	p.LicenseCode = ""
	p.CorpLogoUrl = ""
	p.InviteUrl = ""
	p.InviteCode = ""
	p.IsEcologicalCorp = false
	p.AuthLevel = 0
	p.AuthChannel = ""
	p.AuthChannelType = ""
	p.State = 0
	p.StateTime = time.Time{}
	p.CreatedTime = time.Time{}

}

func (p *Company) TableName() string {
	return CompanyTableName
}

func (p *Company) AssignPtr(args ...dialect.Field) []any {
	if len(args) == 0 {
		args = tblcompany.ReadableFields
	}

	vals := make([]any, 0, len(args))
	for _, col := range args {
		switch col {
		case tblcompany.Id:
			vals = append(vals, &p.Id)
		case tblcompany.Platform:
			vals = append(vals, &p.Platform)
		case tblcompany.CorpId:
			vals = append(vals, &p.CorpId)
		case tblcompany.CorpType:
			vals = append(vals, &p.CorpType)
		case tblcompany.FullCorpName:
			vals = append(vals, &p.FullCorpName)
		case tblcompany.CorpType2:
			vals = append(vals, &p.CorpType2)
		case tblcompany.CorpName:
			vals = append(vals, &p.CorpName)
		case tblcompany.Industry:
			vals = append(vals, &p.Industry)
		case tblcompany.IsAuthenticated:
			vals = append(vals, &p.IsAuthenticated)
		case tblcompany.LicenseCode:
			vals = append(vals, &p.LicenseCode)
		case tblcompany.CorpLogoUrl:
			vals = append(vals, &p.CorpLogoUrl)
		case tblcompany.InviteUrl:
			vals = append(vals, &p.InviteUrl)
		case tblcompany.InviteCode:
			vals = append(vals, &p.InviteCode)
		case tblcompany.IsEcologicalCorp:
			vals = append(vals, &p.IsEcologicalCorp)
		case tblcompany.AuthLevel:
			vals = append(vals, &p.AuthLevel)
		case tblcompany.AuthChannel:
			vals = append(vals, &p.AuthChannel)
		case tblcompany.AuthChannelType:
			vals = append(vals, &p.AuthChannelType)
		case tblcompany.State:
			vals = append(vals, &p.State)
		case tblcompany.StateTime:
			vals = append(vals, &p.StateTime)
		case tblcompany.CreatedTime:
			vals = append(vals, &p.CreatedTime)
		}
	}

	return vals
}

func (p *Company) Scan(rows *sql.Rows, args ...dialect.Field) ([]*Company, bool, error) {
	defer rows.Close()
	companys := make([]*Company, 0)

	if len(args) == 0 {
		args = tblcompany.ReadableFields
	}

	for rows.Next() {
		p := NewCompany()
		vals := p.AssignPtr(args...)
		err := rows.Scan(vals...)
		if err != nil {
			return nil, false, err
		}
		companys = append(companys, p)
	}
	if err := rows.Err(); err != nil {
		return nil, false, err
	}
	if len(companys) == 0 {
		return nil, false, sql.ErrNoRows
	}
	return companys, true, nil
}

func (p *Company) AssignValues(args ...dialect.Field) ([]string, []any) {
	var (
		lens = len(args)
		cols []string
		vals []any
	)

	if len(args) == 0 {
		args = tblcompany.WritableFields
		lens = len(args)
		cols = make([]string, 0, lens)
		vals = make([]any, 0, lens)
		for _, arg := range args {
			switch arg {
			case tblcompany.Id:
				if p.Id == 0 {
					continue
				}
				cols = append(cols, tblcompany.Id.Quote())
				vals = append(vals, p.Id)
			case tblcompany.Platform:
				if p.Platform == "" {
					continue
				}
				cols = append(cols, tblcompany.Platform.Quote())
				vals = append(vals, p.Platform)
			case tblcompany.CorpId:
				if p.CorpId == "" {
					continue
				}
				cols = append(cols, tblcompany.CorpId.Quote())
				vals = append(vals, p.CorpId)
			case tblcompany.CorpType:
				if p.CorpType == 0 {
					continue
				}
				cols = append(cols, tblcompany.CorpType.Quote())
				vals = append(vals, p.CorpType)
			case tblcompany.FullCorpName:
				if p.FullCorpName == "" {
					continue
				}
				cols = append(cols, tblcompany.FullCorpName.Quote())
				vals = append(vals, p.FullCorpName)
			case tblcompany.CorpType2:
				if p.CorpType2 == 0 {
					continue
				}
				cols = append(cols, tblcompany.CorpType2.Quote())
				vals = append(vals, p.CorpType2)
			case tblcompany.CorpName:
				if p.CorpName == "" {
					continue
				}
				cols = append(cols, tblcompany.CorpName.Quote())
				vals = append(vals, p.CorpName)
			case tblcompany.Industry:
				if p.Industry == "" {
					continue
				}
				cols = append(cols, tblcompany.Industry.Quote())
				vals = append(vals, p.Industry)
			case tblcompany.IsAuthenticated:
				if p.IsAuthenticated == false {
					continue
				}
				cols = append(cols, tblcompany.IsAuthenticated.Quote())
				vals = append(vals, p.IsAuthenticated)
			case tblcompany.LicenseCode:
				if p.LicenseCode == "" {
					continue
				}
				cols = append(cols, tblcompany.LicenseCode.Quote())
				vals = append(vals, p.LicenseCode)
			case tblcompany.CorpLogoUrl:
				if p.CorpLogoUrl == "" {
					continue
				}
				cols = append(cols, tblcompany.CorpLogoUrl.Quote())
				vals = append(vals, p.CorpLogoUrl)
			case tblcompany.InviteUrl:
				if p.InviteUrl == "" {
					continue
				}
				cols = append(cols, tblcompany.InviteUrl.Quote())
				vals = append(vals, p.InviteUrl)
			case tblcompany.InviteCode:
				if p.InviteCode == "" {
					continue
				}
				cols = append(cols, tblcompany.InviteCode.Quote())
				vals = append(vals, p.InviteCode)
			case tblcompany.IsEcologicalCorp:
				if p.IsEcologicalCorp == false {
					continue
				}
				cols = append(cols, tblcompany.IsEcologicalCorp.Quote())
				vals = append(vals, p.IsEcologicalCorp)
			case tblcompany.AuthLevel:
				if p.AuthLevel == 0 {
					continue
				}
				cols = append(cols, tblcompany.AuthLevel.Quote())
				vals = append(vals, p.AuthLevel)
			case tblcompany.AuthChannel:
				if p.AuthChannel == "" {
					continue
				}
				cols = append(cols, tblcompany.AuthChannel.Quote())
				vals = append(vals, p.AuthChannel)
			case tblcompany.AuthChannelType:
				if p.AuthChannelType == "" {
					continue
				}
				cols = append(cols, tblcompany.AuthChannelType.Quote())
				vals = append(vals, p.AuthChannelType)
			case tblcompany.State:
				if p.State == 0 {
					continue
				}
				cols = append(cols, tblcompany.State.Quote())
				vals = append(vals, p.State)
			case tblcompany.StateTime:
				if p.StateTime.IsZero() {
					continue
				}
				cols = append(cols, tblcompany.StateTime.Quote())
				vals = append(vals, p.StateTime)
			case tblcompany.CreatedTime:
				if p.CreatedTime.IsZero() {
					continue
				}
				cols = append(cols, tblcompany.CreatedTime.Quote())
				vals = append(vals, p.CreatedTime)
			}
		}
		return cols, vals
	}

	cols = make([]string, 0, lens)
	vals = make([]any, 0, lens)
	for _, arg := range args {
		switch arg {
		case tblcompany.Id:
			cols = append(cols, tblcompany.Id.Quote())
			vals = append(vals, p.Id)
		case tblcompany.Platform:
			cols = append(cols, tblcompany.Platform.Quote())
			vals = append(vals, p.Platform)
		case tblcompany.CorpId:
			cols = append(cols, tblcompany.CorpId.Quote())
			vals = append(vals, p.CorpId)
		case tblcompany.CorpType:
			cols = append(cols, tblcompany.CorpType.Quote())
			vals = append(vals, p.CorpType)
		case tblcompany.FullCorpName:
			cols = append(cols, tblcompany.FullCorpName.Quote())
			vals = append(vals, p.FullCorpName)
		case tblcompany.CorpType2:
			cols = append(cols, tblcompany.CorpType2.Quote())
			vals = append(vals, p.CorpType2)
		case tblcompany.CorpName:
			cols = append(cols, tblcompany.CorpName.Quote())
			vals = append(vals, p.CorpName)
		case tblcompany.Industry:
			cols = append(cols, tblcompany.Industry.Quote())
			vals = append(vals, p.Industry)
		case tblcompany.IsAuthenticated:
			cols = append(cols, tblcompany.IsAuthenticated.Quote())
			vals = append(vals, p.IsAuthenticated)
		case tblcompany.LicenseCode:
			cols = append(cols, tblcompany.LicenseCode.Quote())
			vals = append(vals, p.LicenseCode)
		case tblcompany.CorpLogoUrl:
			cols = append(cols, tblcompany.CorpLogoUrl.Quote())
			vals = append(vals, p.CorpLogoUrl)
		case tblcompany.InviteUrl:
			cols = append(cols, tblcompany.InviteUrl.Quote())
			vals = append(vals, p.InviteUrl)
		case tblcompany.InviteCode:
			cols = append(cols, tblcompany.InviteCode.Quote())
			vals = append(vals, p.InviteCode)
		case tblcompany.IsEcologicalCorp:
			cols = append(cols, tblcompany.IsEcologicalCorp.Quote())
			vals = append(vals, p.IsEcologicalCorp)
		case tblcompany.AuthLevel:
			cols = append(cols, tblcompany.AuthLevel.Quote())
			vals = append(vals, p.AuthLevel)
		case tblcompany.AuthChannel:
			cols = append(cols, tblcompany.AuthChannel.Quote())
			vals = append(vals, p.AuthChannel)
		case tblcompany.AuthChannelType:
			cols = append(cols, tblcompany.AuthChannelType.Quote())
			vals = append(vals, p.AuthChannelType)
		case tblcompany.State:
			cols = append(cols, tblcompany.State.Quote())
			vals = append(vals, p.State)
		case tblcompany.StateTime:
			cols = append(cols, tblcompany.StateTime.Quote())
			vals = append(vals, p.StateTime)
		case tblcompany.CreatedTime:
			cols = append(cols, tblcompany.CreatedTime.Quote())
			vals = append(vals, p.CreatedTime)
		}
	}
	return cols, vals
}

func (p *Company) AssignKeys() (dialect.Field, any) {
	return tblcompany.PrimaryKey, p.Id
}

func (p *Company) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
