// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package db

import (
	"database/sql"
	"github.com/linbaozhong/gentity/example/model/define/table/tblapp"
	"github.com/linbaozhong/gentity/pkg/ace"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/types"
)

const AppTableName = "app"

var (
	appPool = pool.New(ace.Context, func() any {
		obj := &App{}
		obj.UUID()
		return obj
	})
)

func NewApp() *App {
	obj := appPool.Get().(*App)
	return obj
}

// Free
func (p *App) Free() {
	if p == nil {
		return
	}

	appPool.Put(p)
}

// Reset
func (p *App) Reset() {
	p.Id = 0
	p.Arch = ""
	p.Version = ""
	p.Url = ""
	p.State = 0
	p.Force = 0
	p.Ctime = types.AceTime{}

}

func (p *App) TableName() string {
	return AppTableName
}

func (p *App) AssignPtr(args ...dialect.Field) []any {
	if len(args) == 0 {
		args = tblapp.ReadableFields
	}

	vals := make([]any, 0, len(args))
	for _, col := range args {
		switch col {
		case tblapp.Id:
			vals = append(vals, &p.Id)
		case tblapp.Arch:
			vals = append(vals, &p.Arch)
		case tblapp.Version:
			vals = append(vals, &p.Version)
		case tblapp.Url:
			vals = append(vals, &p.Url)
		case tblapp.State:
			vals = append(vals, &p.State)
		case tblapp.Force:
			vals = append(vals, &p.Force)
		case tblapp.Ctime:
			vals = append(vals, &p.Ctime)
		}
	}

	return vals
}

func (p *App) Scan(rows *sql.Rows, args ...dialect.Field) ([]*App, bool, error) {
	defer rows.Close()
	apps := make([]*App, 0)

	if len(args) == 0 {
		args = tblapp.ReadableFields
	}

	for rows.Next() {
		p := NewApp()
		vals := p.AssignPtr(args...)
		err := rows.Scan(vals...)
		if err != nil {
			return nil, false, err
		}
		apps = append(apps, p)
	}
	if err := rows.Err(); err != nil {
		return nil, false, err
	}
	if len(apps) == 0 {
		return nil, false, sql.ErrNoRows
	}
	return apps, true, nil
}

func (p *App) AssignValues(args ...dialect.Field) ([]string, []any) {
	var (
		lens = len(args)
		cols []string
		vals []any
	)

	if len(args) == 0 {
		args = tblapp.WritableFields
		lens = len(args)
		cols = make([]string, 0, lens)
		vals = make([]any, 0, lens)
		for _, arg := range args {
			switch arg {
			case tblapp.Id:
				if p.Id == 0 {
					continue
				}
				cols = append(cols, tblapp.Id.Quote())
				vals = append(vals, p.Id)
			case tblapp.Arch:
				if p.Arch == "" {
					continue
				}
				cols = append(cols, tblapp.Arch.Quote())
				vals = append(vals, p.Arch)
			case tblapp.Version:
				if p.Version == "" {
					continue
				}
				cols = append(cols, tblapp.Version.Quote())
				vals = append(vals, p.Version)
			case tblapp.Url:
				if p.Url == "" {
					continue
				}
				cols = append(cols, tblapp.Url.Quote())
				vals = append(vals, p.Url)
			case tblapp.State:
				if p.State == 0 {
					continue
				}
				cols = append(cols, tblapp.State.Quote())
				vals = append(vals, p.State)
			case tblapp.Force:
				if p.Force == 0 {
					continue
				}
				cols = append(cols, tblapp.Force.Quote())
				vals = append(vals, p.Force)
			case tblapp.Ctime:
				if p.Ctime.IsZero() {
					continue
				}
				cols = append(cols, tblapp.Ctime.Quote())
				vals = append(vals, p.Ctime)
			}
		}
		return cols, vals
	}

	cols = make([]string, 0, lens)
	vals = make([]any, 0, lens)
	for _, arg := range args {
		switch arg {
		case tblapp.Id:
			cols = append(cols, tblapp.Id.Quote())
			vals = append(vals, p.Id)
		case tblapp.Arch:
			cols = append(cols, tblapp.Arch.Quote())
			vals = append(vals, p.Arch)
		case tblapp.Version:
			cols = append(cols, tblapp.Version.Quote())
			vals = append(vals, p.Version)
		case tblapp.Url:
			cols = append(cols, tblapp.Url.Quote())
			vals = append(vals, p.Url)
		case tblapp.State:
			cols = append(cols, tblapp.State.Quote())
			vals = append(vals, p.State)
		case tblapp.Force:
			cols = append(cols, tblapp.Force.Quote())
			vals = append(vals, p.Force)
		case tblapp.Ctime:
			cols = append(cols, tblapp.Ctime.Quote())
			vals = append(vals, p.Ctime)
		}
	}
	return cols, vals
}

func (p *App) AssignKeys() (dialect.Field, any) {
	return tblapp.PrimaryKey, p.Id
}

func (p *App) AssignPrimaryKeyValues(result sql.Result) error {
	id, err := result.LastInsertId()
	if err != nil {
		return err
	}
	p.Id = types.AceInt(id)
	return nil
}
