// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"bytes"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/example/model/define/table/tblapp"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/app"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

const AppTableName = "app"

var (
	appPool = pool.New(app.Context, func() any {
		_obj := &App{}
		_obj.UUID()
		return _obj
	})
)

func NewApp() *App {
	_obj := appPool.Get().(*App)
	return _obj
}

// MarshalJSON
func (p *App) MarshalJSON() ([]byte, error) {
	var _buf = bytes.NewBuffer(nil)
	_buf.WriteByte('{')
	if p.Id != 0 {
		_buf.WriteString(`"id":` + types.Marshal(p.Id) + `,`)
	}
	if p.Arch != "" {
		_buf.WriteString(`"arch":` + types.Marshal(p.Arch) + `,`)
	}
	if p.Version != "" {
		_buf.WriteString(`"version":` + types.Marshal(p.Version) + `,`)
	}
	if p.Url != "" {
		_buf.WriteString(`"url":` + types.Marshal(p.Url) + `,`)
	}
	if p.State != 0 {
		_buf.WriteString(`"state":` + types.Marshal(p.State) + `,`)
	}
	if p.Force != 0 {
		_buf.WriteString(`"force":` + types.Marshal(p.Force) + `,`)
	}
	if l := _buf.Len(); l > 1 {
		_buf.Truncate(l - 1)
	}
	_buf.WriteByte('}')
	return _buf.Bytes(), nil
}

// UnmarshalJSON
func (p *App) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "id":
			e = types.Unmarshal(value, &p.Id, types.BigInt(value.Uint()))
		case "arch":
			e = types.Unmarshal(value, &p.Arch, types.String(value.Str))
		case "version":
			e = types.Unmarshal(value, &p.Version, types.String(value.Str))
		case "url":
			e = types.Unmarshal(value, &p.Url, types.String(value.Str))
		case "state":
			e = types.Unmarshal(value, &p.State, types.Int8(value.Int()))
		case "force":
			e = types.Unmarshal(value, &p.Force, types.Int8(value.Int()))
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *App) Free() {
	if p == nil {
		return
	}

	appPool.Put(p)
}

// Reset
func (p *App) Reset() {
	p.Id = 0
	p.Arch = ""
	p.Version = ""
	p.Url = ""
	p.State = 0
	p.Force = 0

}

func (p *App) TableName() string {
	return AppTableName
}

func (p *App) AssignPtr(args ...dialect.Field) []any {
	if len(args) == 0 {
		args = tblapp.ReadableFields
	}

	_vals := make([]any, 0, len(args))
	for _, col := range args {
		switch col {
		case tblapp.Id:
			_vals = append(_vals, &p.Id)
		case tblapp.Arch:
			_vals = append(_vals, &p.Arch)
		case tblapp.Version:
			_vals = append(_vals, &p.Version)
		case tblapp.Url:
			_vals = append(_vals, &p.Url)
		case tblapp.State:
			_vals = append(_vals, &p.State)
		case tblapp.Force:
			_vals = append(_vals, &p.Force)
		}
	}

	return _vals
}

func (p *App) Scan(rows *sql.Rows, args ...dialect.Field) ([]App, bool, error) {
	defer rows.Close()
	apps := make([]App, 0)

	if len(args) == 0 {
		args = tblapp.ReadableFields
	}

	for rows.Next() {
		_p := NewApp()
		_vals := _p.AssignPtr(args...)
		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		apps = append(apps, *_p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	if len(apps) == 0 {
		return nil, false, sql.ErrNoRows
	}
	return apps, true, nil
}

func (p *App) AssignValues(args ...dialect.Field) ([]string, []any) {
	var (
		_lens = len(args)
		_cols []string
		_vals []any
	)

	if len(args) == 0 {
		args = tblapp.WritableFields
		_lens = len(args)
		_cols = make([]string, 0, _lens)
		_vals = make([]any, 0, _lens)
		for _, arg := range args {
			switch arg {
			case tblapp.Id:
				if p.Id == 0 {
					continue
				}
				_cols = append(_cols, tblapp.Id.Quote())
				_vals = append(_vals, p.Id)
			case tblapp.Arch:
				if p.Arch == "" {
					continue
				}
				_cols = append(_cols, tblapp.Arch.Quote())
				_vals = append(_vals, p.Arch)
			case tblapp.Version:
				if p.Version == "" {
					continue
				}
				_cols = append(_cols, tblapp.Version.Quote())
				_vals = append(_vals, p.Version)
			case tblapp.Url:
				if p.Url == "" {
					continue
				}
				_cols = append(_cols, tblapp.Url.Quote())
				_vals = append(_vals, p.Url)
			case tblapp.State:
				if p.State == 0 {
					continue
				}
				_cols = append(_cols, tblapp.State.Quote())
				_vals = append(_vals, p.State)
			case tblapp.Force:
				if p.Force == 0 {
					continue
				}
				_cols = append(_cols, tblapp.Force.Quote())
				_vals = append(_vals, p.Force)
			}
		}
		return _cols, _vals
	}

	_cols = make([]string, 0, _lens)
	_vals = make([]any, 0, _lens)
	for _, arg := range args {
		switch arg {
		case tblapp.Id:
			_cols = append(_cols, tblapp.Id.Quote())
			_vals = append(_vals, p.Id)
		case tblapp.Arch:
			_cols = append(_cols, tblapp.Arch.Quote())
			_vals = append(_vals, p.Arch)
		case tblapp.Version:
			_cols = append(_cols, tblapp.Version.Quote())
			_vals = append(_vals, p.Version)
		case tblapp.Url:
			_cols = append(_cols, tblapp.Url.Quote())
			_vals = append(_vals, p.Url)
		case tblapp.State:
			_cols = append(_cols, tblapp.State.Quote())
			_vals = append(_vals, p.State)
		case tblapp.Force:
			_cols = append(_cols, tblapp.Force.Quote())
			_vals = append(_vals, p.Force)
		}
	}
	return _cols, _vals
}

func (p *App) AssignKeys() (dialect.Field, any) {
	return tblapp.PrimaryKey, p.Id
}

func (p *App) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
