// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"bytes"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/example/model/define/table/tblusers"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/app"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

const UsersTableName = "users"

var (
	usersPool = pool.New(app.Context, func() any {
		_obj := &Users{}
		_obj.UUID()
		return _obj
	})
)

func NewUsers() *Users {
	_obj := usersPool.Get().(*Users)
	return _obj
}

// MarshalJSON
func (p *Users) MarshalJSON() ([]byte, error) {
	var _buf = bytes.NewBuffer(nil)
	_buf.WriteByte('{')
	if p.Id != 0 {
		_buf.WriteString(`"id":` + types.Marshal(p.Id) + `,`)
	}
	if p.From != "" {
		_buf.WriteString(`"from":` + types.Marshal(p.From) + `,`)
	}
	if p.OpenId != "" {
		_buf.WriteString(`"open_id":` + types.Marshal(p.OpenId) + `,`)
	}
	if p.UnionId != "" {
		_buf.WriteString(`"union_id":` + types.Marshal(p.UnionId) + `,`)
	}
	if p.SessionKey != "" {
		_buf.WriteString(`"session_key":` + types.Marshal(p.SessionKey) + `,`)
	}
	if p.Mobile != "" {
		_buf.WriteString(`"mobile":` + types.Marshal(p.Mobile) + `,`)
	}
	if p.Email != "" {
		_buf.WriteString(`"email":` + types.Marshal(p.Email) + `,`)
	}
	if p.Pwd != "" {
		_buf.WriteString(`"pwd":` + types.Marshal(p.Pwd) + `,`)
	}
	if p.Avatar != "" {
		_buf.WriteString(`"avatar":` + types.Marshal(p.Avatar) + `,`)
	}
	if p.Nick != "" {
		_buf.WriteString(`"nick":` + types.Marshal(p.Nick) + `,`)
	}
	if p.Gender != "" {
		_buf.WriteString(`"gender":` + types.Marshal(p.Gender) + `,`)
	}
	if p.State != 0 {
		_buf.WriteString(`"state":` + types.Marshal(p.State) + `,`)
	}
	if !p.Ctime.IsZero() {
		_buf.WriteString(`"ctime":` + types.Marshal(p.Ctime) + `,`)
	}
	if l := _buf.Len(); l > 1 {
		_buf.Truncate(l - 1)
	}
	_buf.WriteByte('}')
	return _buf.Bytes(), nil
}

// UnmarshalJSON
func (p *Users) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "from":
			p.From = types.String(value.Str)
		case "open_id":
			p.OpenId = types.String(value.Str)
		case "union_id":
			p.UnionId = types.String(value.Str)
		case "session_key":
			p.SessionKey = types.String(value.Str)
		case "mobile":
			p.Mobile = types.String(value.Str)
		case "email":
			p.Email = types.String(value.Str)
		case "pwd":
			p.Pwd = types.String(value.Str)
		case "avatar":
			p.Avatar = types.String(value.Str)
		case "nick":
			p.Nick = types.String(value.Str)
		case "gender":
			p.Gender = types.String(value.Str)
		case "state":
			p.State = types.Int8(value.Int())
		case "ctime":
			p.Ctime = types.Time{Time: value.Time()}
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *Users) Free() {
	if p == nil {
		return
	}

	usersPool.Put(p)
}

// Reset
func (p *Users) Reset() {
	p.Id = 0
	p.From = ""
	p.OpenId = ""
	p.UnionId = ""
	p.SessionKey = ""
	p.Mobile = ""
	p.Email = ""
	p.Pwd = ""
	p.Avatar = ""
	p.Nick = ""
	p.Gender = ""
	p.State = 0
	p.Ctime = types.Time{}

}

func (p *Users) TableName() string {
	return UsersTableName
}

func (p *Users) AssignPtr(args ...dialect.Field) []any {
	if len(args) == 0 {
		args = tblusers.ReadableFields
	}

	_vals := make([]any, 0, len(args))
	for _, col := range args {
		switch col {
		case tblusers.Id:
			_vals = append(_vals, &p.Id)
		case tblusers.From:
			_vals = append(_vals, &p.From)
		case tblusers.OpenId:
			_vals = append(_vals, &p.OpenId)
		case tblusers.UnionId:
			_vals = append(_vals, &p.UnionId)
		case tblusers.SessionKey:
			_vals = append(_vals, &p.SessionKey)
		case tblusers.Mobile:
			_vals = append(_vals, &p.Mobile)
		case tblusers.Email:
			_vals = append(_vals, &p.Email)
		case tblusers.Pwd:
			_vals = append(_vals, &p.Pwd)
		case tblusers.Avatar:
			_vals = append(_vals, &p.Avatar)
		case tblusers.Nick:
			_vals = append(_vals, &p.Nick)
		case tblusers.Gender:
			_vals = append(_vals, &p.Gender)
		case tblusers.State:
			_vals = append(_vals, &p.State)
		case tblusers.Ctime:
			_vals = append(_vals, &p.Ctime)
		}
	}

	return _vals
}

func (p *Users) Scan(rows *sql.Rows, args ...dialect.Field) ([]Users, bool, error) {
	defer rows.Close()
	userss := make([]Users, 0)

	if len(args) == 0 {
		args = tblusers.ReadableFields
	}

	for rows.Next() {
		_p := NewUsers()
		_vals := _p.AssignPtr(args...)
		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		userss = append(userss, *_p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return userss, len(userss) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Users) RawAssignValues(args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblusers.WritableFields
	}
	return p.AssignValues(args...)
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *Users) AssignValues(args ...dialect.Field) ([]string, []any) {
	var (
		_lens = len(args)
		_cols []string
		_vals []any
	)

	if len(args) == 0 {
		args = tblusers.WritableFields
		_lens = len(args)
		_cols = make([]string, 0, _lens)
		_vals = make([]any, 0, _lens)
		for _, arg := range args {
			switch arg {
			case tblusers.Id:
				if p.Id == 0 {
					continue
				}
				_cols = append(_cols, tblusers.Id.Quote())
				_vals = append(_vals, p.Id)
			case tblusers.From:
				if p.From == "" {
					continue
				}
				_cols = append(_cols, tblusers.From.Quote())
				_vals = append(_vals, p.From)
			case tblusers.OpenId:
				if p.OpenId == "" {
					continue
				}
				_cols = append(_cols, tblusers.OpenId.Quote())
				_vals = append(_vals, p.OpenId)
			case tblusers.UnionId:
				if p.UnionId == "" {
					continue
				}
				_cols = append(_cols, tblusers.UnionId.Quote())
				_vals = append(_vals, p.UnionId)
			case tblusers.SessionKey:
				if p.SessionKey == "" {
					continue
				}
				_cols = append(_cols, tblusers.SessionKey.Quote())
				_vals = append(_vals, p.SessionKey)
			case tblusers.Mobile:
				if p.Mobile == "" {
					continue
				}
				_cols = append(_cols, tblusers.Mobile.Quote())
				_vals = append(_vals, p.Mobile)
			case tblusers.Email:
				if p.Email == "" {
					continue
				}
				_cols = append(_cols, tblusers.Email.Quote())
				_vals = append(_vals, p.Email)
			case tblusers.Pwd:
				if p.Pwd == "" {
					continue
				}
				_cols = append(_cols, tblusers.Pwd.Quote())
				_vals = append(_vals, p.Pwd)
			case tblusers.Avatar:
				if p.Avatar == "" {
					continue
				}
				_cols = append(_cols, tblusers.Avatar.Quote())
				_vals = append(_vals, p.Avatar)
			case tblusers.Nick:
				if p.Nick == "" {
					continue
				}
				_cols = append(_cols, tblusers.Nick.Quote())
				_vals = append(_vals, p.Nick)
			case tblusers.Gender:
				if p.Gender == "" {
					continue
				}
				_cols = append(_cols, tblusers.Gender.Quote())
				_vals = append(_vals, p.Gender)
			case tblusers.State:
				if p.State == 0 {
					continue
				}
				_cols = append(_cols, tblusers.State.Quote())
				_vals = append(_vals, p.State)
			case tblusers.Ctime:
				if p.Ctime.IsZero() {
					continue
				}
				_cols = append(_cols, tblusers.Ctime.Quote())
				_vals = append(_vals, p.Ctime)
			}
		}
		return _cols, _vals
	}

	_cols = make([]string, 0, _lens)
	_vals = make([]any, 0, _lens)
	for _, arg := range args {
		switch arg {
		case tblusers.Id:
			_cols = append(_cols, tblusers.Id.Quote())
			_vals = append(_vals, p.Id)
		case tblusers.From:
			_cols = append(_cols, tblusers.From.Quote())
			_vals = append(_vals, p.From)
		case tblusers.OpenId:
			_cols = append(_cols, tblusers.OpenId.Quote())
			_vals = append(_vals, p.OpenId)
		case tblusers.UnionId:
			_cols = append(_cols, tblusers.UnionId.Quote())
			_vals = append(_vals, p.UnionId)
		case tblusers.SessionKey:
			_cols = append(_cols, tblusers.SessionKey.Quote())
			_vals = append(_vals, p.SessionKey)
		case tblusers.Mobile:
			_cols = append(_cols, tblusers.Mobile.Quote())
			_vals = append(_vals, p.Mobile)
		case tblusers.Email:
			_cols = append(_cols, tblusers.Email.Quote())
			_vals = append(_vals, p.Email)
		case tblusers.Pwd:
			_cols = append(_cols, tblusers.Pwd.Quote())
			_vals = append(_vals, p.Pwd)
		case tblusers.Avatar:
			_cols = append(_cols, tblusers.Avatar.Quote())
			_vals = append(_vals, p.Avatar)
		case tblusers.Nick:
			_cols = append(_cols, tblusers.Nick.Quote())
			_vals = append(_vals, p.Nick)
		case tblusers.Gender:
			_cols = append(_cols, tblusers.Gender.Quote())
			_vals = append(_vals, p.Gender)
		case tblusers.State:
			_cols = append(_cols, tblusers.State.Quote())
			_vals = append(_vals, p.State)
		case tblusers.Ctime:
			_cols = append(_cols, tblusers.Ctime.Quote())
			_vals = append(_vals, p.Ctime)
		}
	}
	return _cols, _vals
}

func (p *Users) AssignKeys() (dialect.Field, any) {
	return tblusers.PrimaryKey, p.Id
}

func (p *Users) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
