// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"bytes"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/example/model/define/table/tblcompanyrole"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/app"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

const CompanyRoleTableName = "company_role"

var (
	companyrolePool = pool.New(app.Context, func() any {
		_obj := &CompanyRole{}
		return _obj
	})
)

func NewCompanyRole() *CompanyRole {
	_obj := companyrolePool.Get().(*CompanyRole)
	return _obj
}

// MarshalJSON
func (p *CompanyRole) MarshalJSON() ([]byte, error) {
	var (
		_buf   = bytes.NewBuffer((make([]byte, 0, 7*50)))
		_comma bool
	)
	_buf.WriteByte('{')

	writeField := func(key string, value string) {
		if _comma {
			_buf.WriteByte(',')
		}
		_buf.WriteByte('"')
		_buf.WriteString(key)
		_buf.WriteString(`":`)
		_buf.WriteString(value)
		_comma = true
	}
	if p.Id != 0 {
		writeField("id", types.Marshal(p.Id))
	}
	if p.Company != 0 {
		writeField("company", types.Marshal(p.Company))
	}
	if p.Name != "" {
		writeField("name", types.Marshal(p.Name))
	}
	if p.Descr != "" {
		writeField("descr", types.Marshal(p.Descr))
	}
	if p.Rules != "" {
		writeField("rules", types.Marshal(p.Rules))
	}
	if p.Type != 0 {
		writeField("type", types.Marshal(p.Type))
	}
	if p.State != 0 {
		writeField("state", types.Marshal(p.State))
	}
	_buf.WriteByte('}')
	return _buf.Bytes(), nil
}

// UnmarshalJSON
func (p *CompanyRole) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "company":
			p.Company = types.BigInt(value.Uint())
		case "name":
			p.Name = types.String(value.Str)
		case "descr":
			p.Descr = types.String(value.Str)
		case "rules":
			p.Rules = types.String(value.Str)
		case "type":
			p.Type = types.Int8(value.Int())
		case "state":
			p.State = types.Int8(value.Int())
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *CompanyRole) Free() {
	if p == nil {
		return
	}

	companyrolePool.Put(p)
}

// Reset
func (p *CompanyRole) Reset() {
	p.Id = 0
	p.Company = 0
	p.Name = ""
	p.Descr = ""
	p.Rules = ""
	p.Type = 0
	p.State = 0

}

func (p *CompanyRole) TableName() string {
	return CompanyRoleTableName
}

// 定义一个映射表，将字段与对应的指针获取函数关联
var companyroleFieldToPtrFunc = map[dialect.Field]func(*CompanyRole) any{
	tblcompanyrole.Id:      func(p *CompanyRole) any { return &p.Id },
	tblcompanyrole.Company: func(p *CompanyRole) any { return &p.Company },
	tblcompanyrole.Name:    func(p *CompanyRole) any { return &p.Name },
	tblcompanyrole.Descr:   func(p *CompanyRole) any { return &p.Descr },
	tblcompanyrole.Rules:   func(p *CompanyRole) any { return &p.Rules },
	tblcompanyrole.Type:    func(p *CompanyRole) any { return &p.Type },
	tblcompanyrole.State:   func(p *CompanyRole) any { return &p.State },
}

// AssignPtr 根据传入的字段参数，返回对应字段的指针切片。
// 如果未传入任何字段参数，则默认使用 ReadableFields 中的字段。
// 参数 args 为可变参数，代表需要获取指针的字段。
// 返回值为一个包含对应字段指针的切片。
func (p *CompanyRole) AssignPtr(args ...dialect.Field) []any {
	if len(args) == 0 {
		args = tblcompanyrole.ReadableFields
	}

	_vals := make([]any, 0, len(args))
	for _, col := range args {
		if ptrFunc, ok := companyroleFieldToPtrFunc[col]; ok {
			_vals = append(_vals, ptrFunc(p))
		}
	}

	return _vals
}

func (p *CompanyRole) Scan(rows *sql.Rows, args ...dialect.Field) ([]*CompanyRole, bool, error) {
	defer rows.Close()
	company_roles := make([]*CompanyRole, 0)

	if len(args) == 0 {
		args = tblcompanyrole.ReadableFields
	}

	for rows.Next() {
		_p := NewCompanyRole()
		_vals := _p.AssignPtr(args...)
		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		company_roles = append(company_roles, _p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return company_roles, len(company_roles) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *CompanyRole) RawAssignValues(args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblcompanyrole.WritableFields
	}
	return p.AssignValues(args...)
}

// 定义字段到值检查和获取函数的映射
var companyroleFieldToValueFunc = map[dialect.Field]func(*CompanyRole) (string, any, bool){
	tblcompanyrole.Id: func(p *CompanyRole) (string, any, bool) {
		return tblcompanyrole.Id.Quote(), p.Id, p.Id == 0
	},
	tblcompanyrole.Company: func(p *CompanyRole) (string, any, bool) {
		return tblcompanyrole.Company.Quote(), p.Company, p.Company == 0
	},
	tblcompanyrole.Name: func(p *CompanyRole) (string, any, bool) {
		return tblcompanyrole.Name.Quote(), p.Name, p.Name == ""
	},
	tblcompanyrole.Descr: func(p *CompanyRole) (string, any, bool) {
		return tblcompanyrole.Descr.Quote(), p.Descr, p.Descr == ""
	},
	tblcompanyrole.Rules: func(p *CompanyRole) (string, any, bool) {
		return tblcompanyrole.Rules.Quote(), p.Rules, p.Rules == ""
	},
	tblcompanyrole.Type: func(p *CompanyRole) (string, any, bool) {
		return tblcompanyrole.Type.Quote(), p.Type, p.Type == 0
	},
	tblcompanyrole.State: func(p *CompanyRole) (string, any, bool) {
		return tblcompanyrole.State.Quote(), p.State, p.State == 0
	},
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *CompanyRole) AssignValues(args ...dialect.Field) ([]string, []any) {
	var (
		_lens = len(args)
		_cols []string
		_vals []any
	)
	if _lens > 0 {
		_cols = make([]string, 0, _lens)
		_vals = make([]any, 0, _lens)
		for _, arg := range args {
			if valueFunc, exists := companyroleFieldToValueFunc[arg]; exists {
				colName, value, _ := valueFunc(p)
				_cols = append(_cols, colName)
				_vals = append(_vals, value)
			}
		}
		return _cols, _vals
	}

	args = tblcompanyrole.WritableFields
	_lens = len(args)
	_cols = make([]string, 0, _lens)
	_vals = make([]any, 0, _lens)
	for _, arg := range args {
		if valueFunc, exists := companyroleFieldToValueFunc[arg]; exists {
			colName, value, valid := valueFunc(p)
			if !valid {
				_cols = append(_cols, colName)
				_vals = append(_vals, value)
			}
		}
	}
	return _cols, _vals
}

func (p *CompanyRole) AssignKeys() (dialect.Field, any) {
	return tblcompanyrole.PrimaryKey, p.Id
}

func (p *CompanyRole) AssignPrimaryKeyValues(result sql.Result) error {
	_id, e := result.LastInsertId()
	if e != nil {
		return e
	}
	p.Id = types.BigInt(_id)
	return nil
}
