// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"database/sql"
	"github.com/linbaozhong/gentity/example/model/define/table/tbluser_log"
	"github.com/linbaozhong/gentity/pkg/ace"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/types"
)

const UserLogTableName = "user_log"

var (
	userlogPool = pool.New(ace.Context, func() any {
		obj := &UserLog{}
		obj.UUID()
		return obj
	})
)

func NewUserLog() *UserLog {
	obj := userlogPool.Get().(*UserLog)
	return obj
}

// Free
func (p *UserLog) Free() {
	if p == nil {
		return
	}

	userlogPool.Put(p)
}

// Reset
func (p *UserLog) Reset() {
	p.Id = 0
	p.UserId = 0
	p.LoginTime = types.AceTime{}
	p.Device = ""
	p.Os = ""
	p.OsVersion = ""
	p.AppName = ""
	p.AppVersion = ""
	p.Ip = ""

}

func (p *UserLog) TableName() string {
	return UserLogTableName
}

func (p *UserLog) AssignPtr(args ...dialect.Field) []any {
	if len(args) == 0 {
		args = tbluser_log.ReadableFields
	}

	vals := make([]any, 0, len(args))
	for _, col := range args {
		switch col {
		case tbluser_log.Id:
			vals = append(vals, &p.Id)
		case tbluser_log.UserId:
			vals = append(vals, &p.UserId)
		case tbluser_log.LoginTime:
			vals = append(vals, &p.LoginTime)
		case tbluser_log.Device:
			vals = append(vals, &p.Device)
		case tbluser_log.Os:
			vals = append(vals, &p.Os)
		case tbluser_log.OsVersion:
			vals = append(vals, &p.OsVersion)
		case tbluser_log.AppName:
			vals = append(vals, &p.AppName)
		case tbluser_log.AppVersion:
			vals = append(vals, &p.AppVersion)
		case tbluser_log.Ip:
			vals = append(vals, &p.Ip)
		}
	}

	return vals
}

func (p *UserLog) Scan(rows *sql.Rows, args ...dialect.Field) ([]*UserLog, bool, error) {
	defer rows.Close()
	user_logs := make([]*UserLog, 0)

	if len(args) == 0 {
		args = tbluser_log.ReadableFields
	}

	for rows.Next() {
		p := NewUserLog()
		vals := p.AssignPtr(args...)
		err := rows.Scan(vals...)
		if err != nil {
			return nil, false, err
		}
		user_logs = append(user_logs, p)
	}
	if err := rows.Err(); err != nil {
		return nil, false, err
	}
	if len(user_logs) == 0 {
		return nil, false, sql.ErrNoRows
	}
	return user_logs, true, nil
}

func (p *UserLog) AssignValues(args ...dialect.Field) ([]string, []any) {
	var (
		lens = len(args)
		cols []string
		vals []any
	)

	if len(args) == 0 {
		args = tbluser_log.WritableFields
		lens = len(args)
		cols = make([]string, 0, lens)
		vals = make([]any, 0, lens)
		for _, arg := range args {
			switch arg {
			case tbluser_log.Id:
				if p.Id == 0 {
					continue
				}
				cols = append(cols, tbluser_log.Id.Quote())
				vals = append(vals, p.Id)
			case tbluser_log.UserId:
				if p.UserId == 0 {
					continue
				}
				cols = append(cols, tbluser_log.UserId.Quote())
				vals = append(vals, p.UserId)
			case tbluser_log.LoginTime:
				if p.LoginTime.IsZero() {
					continue
				}
				cols = append(cols, tbluser_log.LoginTime.Quote())
				vals = append(vals, p.LoginTime)
			case tbluser_log.Device:
				if p.Device == "" {
					continue
				}
				cols = append(cols, tbluser_log.Device.Quote())
				vals = append(vals, p.Device)
			case tbluser_log.Os:
				if p.Os == "" {
					continue
				}
				cols = append(cols, tbluser_log.Os.Quote())
				vals = append(vals, p.Os)
			case tbluser_log.OsVersion:
				if p.OsVersion == "" {
					continue
				}
				cols = append(cols, tbluser_log.OsVersion.Quote())
				vals = append(vals, p.OsVersion)
			case tbluser_log.AppName:
				if p.AppName == "" {
					continue
				}
				cols = append(cols, tbluser_log.AppName.Quote())
				vals = append(vals, p.AppName)
			case tbluser_log.AppVersion:
				if p.AppVersion == "" {
					continue
				}
				cols = append(cols, tbluser_log.AppVersion.Quote())
				vals = append(vals, p.AppVersion)
			case tbluser_log.Ip:
				if p.Ip == "" {
					continue
				}
				cols = append(cols, tbluser_log.Ip.Quote())
				vals = append(vals, p.Ip)
			}
		}
		return cols, vals
	}

	cols = make([]string, 0, lens)
	vals = make([]any, 0, lens)
	for _, arg := range args {
		switch arg {
		case tbluser_log.Id:
			cols = append(cols, tbluser_log.Id.Quote())
			vals = append(vals, p.Id)
		case tbluser_log.UserId:
			cols = append(cols, tbluser_log.UserId.Quote())
			vals = append(vals, p.UserId)
		case tbluser_log.LoginTime:
			cols = append(cols, tbluser_log.LoginTime.Quote())
			vals = append(vals, p.LoginTime)
		case tbluser_log.Device:
			cols = append(cols, tbluser_log.Device.Quote())
			vals = append(vals, p.Device)
		case tbluser_log.Os:
			cols = append(cols, tbluser_log.Os.Quote())
			vals = append(vals, p.Os)
		case tbluser_log.OsVersion:
			cols = append(cols, tbluser_log.OsVersion.Quote())
			vals = append(vals, p.OsVersion)
		case tbluser_log.AppName:
			cols = append(cols, tbluser_log.AppName.Quote())
			vals = append(vals, p.AppName)
		case tbluser_log.AppVersion:
			cols = append(cols, tbluser_log.AppVersion.Quote())
			vals = append(vals, p.AppVersion)
		case tbluser_log.Ip:
			cols = append(cols, tbluser_log.Ip.Quote())
			vals = append(vals, p.Ip)
		}
	}
	return cols, vals
}

func (p *UserLog) AssignKeys() (dialect.Field, any) {
	return tbluser_log.PrimaryKey, p.Id
}

func (p *UserLog) AssignPrimaryKeyValues(result sql.Result) error {
	id, err := result.LastInsertId()
	if err != nil {
		return err
	}
	p.Id = types.BigInt(id)
	return nil
}
