// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package do

import (
	"bytes"
	"database/sql"
	"errors"
	"github.com/linbaozhong/gentity/example/model/define/table/tblusersinfo"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/ace/pool"
	"github.com/linbaozhong/gentity/pkg/app"
	"github.com/linbaozhong/gentity/pkg/gjson"
	"github.com/linbaozhong/gentity/pkg/log"
	"github.com/linbaozhong/gentity/pkg/types"
)

const UsersInfoTableName = "users_info"

var (
	usersinfoPool = pool.New(app.Context, func() any {
		_obj := &UsersInfo{}
		_obj.UUID()
		return _obj
	})
)

func NewUsersInfo() *UsersInfo {
	_obj := usersinfoPool.Get().(*UsersInfo)
	return _obj
}

// MarshalJSON
func (p *UsersInfo) MarshalJSON() ([]byte, error) {
	var _buf = bytes.NewBuffer(nil)
	_buf.WriteByte('{')
	if p.Id != 0 {
		_buf.WriteString(`"id":` + types.Marshal(p.Id) + `,`)
	}
	if p.Name != "" {
		_buf.WriteString(`"name":` + types.Marshal(p.Name) + `,`)
	}
	if p.IdNumber != "" {
		_buf.WriteString(`"id_number":` + types.Marshal(p.IdNumber) + `,`)
	}
	if p.Country != "" {
		_buf.WriteString(`"country":` + types.Marshal(p.Country) + `,`)
	}
	if p.Province != "" {
		_buf.WriteString(`"province":` + types.Marshal(p.Province) + `,`)
	}
	if p.City != "" {
		_buf.WriteString(`"city":` + types.Marshal(p.City) + `,`)
	}
	if !p.Utime.IsZero() {
		_buf.WriteString(`"utime":` + types.Marshal(p.Utime) + `,`)
	}
	if l := _buf.Len(); l > 1 {
		_buf.Truncate(l - 1)
	}
	_buf.WriteByte('}')
	return _buf.Bytes(), nil
}

// UnmarshalJSON
func (p *UsersInfo) UnmarshalJSON(data []byte) error {

	if !gjson.ValidBytes(data) {
		return errors.New("invalid json")
	}
	_result := gjson.ParseBytes(data)
	_result.ForEach(func(key, value gjson.Result) bool {
		var e error
		switch key.Str {
		case "id":
			p.Id = types.BigInt(value.Uint())
		case "name":
			p.Name = types.String(value.Str)
		case "id_number":
			p.IdNumber = types.String(value.Str)
		case "country":
			p.Country = types.String(value.Str)
		case "province":
			p.Province = types.String(value.Str)
		case "city":
			p.City = types.String(value.Str)
		case "utime":
			p.Utime = types.Time{Time: value.Time()}
		}
		if e != nil {
			log.Error(e)
			return false
		}
		return true
	})
	return nil
}

// Free
func (p *UsersInfo) Free() {
	if p == nil {
		return
	}

	usersinfoPool.Put(p)
}

// Reset
func (p *UsersInfo) Reset() {
	p.Id = 0
	p.Name = ""
	p.IdNumber = ""
	p.Country = ""
	p.Province = ""
	p.City = ""
	p.Utime = types.Time{}

}

func (p *UsersInfo) TableName() string {
	return UsersInfoTableName
}

func (p *UsersInfo) AssignPtr(args ...dialect.Field) []any {
	if len(args) == 0 {
		args = tblusersinfo.ReadableFields
	}

	_vals := make([]any, 0, len(args))
	for _, col := range args {
		switch col {
		case tblusersinfo.Id:
			_vals = append(_vals, &p.Id)
		case tblusersinfo.Name:
			_vals = append(_vals, &p.Name)
		case tblusersinfo.IdNumber:
			_vals = append(_vals, &p.IdNumber)
		case tblusersinfo.Country:
			_vals = append(_vals, &p.Country)
		case tblusersinfo.Province:
			_vals = append(_vals, &p.Province)
		case tblusersinfo.City:
			_vals = append(_vals, &p.City)
		case tblusersinfo.Utime:
			_vals = append(_vals, &p.Utime)
		}
	}

	return _vals
}

func (p *UsersInfo) Scan(rows *sql.Rows, args ...dialect.Field) ([]UsersInfo, bool, error) {
	defer rows.Close()
	users_infos := make([]UsersInfo, 0)

	if len(args) == 0 {
		args = tblusersinfo.ReadableFields
	}

	for rows.Next() {
		_p := NewUsersInfo()
		_vals := _p.AssignPtr(args...)
		e := rows.Scan(_vals...)
		if e != nil {
			log.Error(e)
			return nil, false, e
		}
		users_infos = append(users_infos, *_p)
	}
	if e := rows.Err(); e != nil {
		log.Error(e)
		return nil, false, e
	}
	return users_infos, len(users_infos) > 0, nil
}

// RawAssignValues 向数据库写入数据前，为表列赋值。多用于批量插入和更新
// 如果 args 为空，则赋值所有可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *UsersInfo) RawAssignValues(args ...dialect.Field) ([]string, []any) {
	if len(args) == 0 {
		args = tblusersinfo.WritableFields
	}
	return p.AssignValues(args...)
}

// AssignValues 向数据库写入数据前，为表列赋值。
// 如果 args 为空，则将非零值赋与可写字段
// 如果 args 不为空，则只赋值 args 中的字段
func (p *UsersInfo) AssignValues(args ...dialect.Field) ([]string, []any) {
	var (
		_lens = len(args)
		_cols []string
		_vals []any
	)

	if len(args) == 0 {
		args = tblusersinfo.WritableFields
		_lens = len(args)
		_cols = make([]string, 0, _lens)
		_vals = make([]any, 0, _lens)
		for _, arg := range args {
			switch arg {
			case tblusersinfo.Id:
				if p.Id == 0 {
					continue
				}
				_cols = append(_cols, tblusersinfo.Id.Quote())
				_vals = append(_vals, p.Id)
			case tblusersinfo.Name:
				if p.Name == "" {
					continue
				}
				_cols = append(_cols, tblusersinfo.Name.Quote())
				_vals = append(_vals, p.Name)
			case tblusersinfo.IdNumber:
				if p.IdNumber == "" {
					continue
				}
				_cols = append(_cols, tblusersinfo.IdNumber.Quote())
				_vals = append(_vals, p.IdNumber)
			case tblusersinfo.Country:
				if p.Country == "" {
					continue
				}
				_cols = append(_cols, tblusersinfo.Country.Quote())
				_vals = append(_vals, p.Country)
			case tblusersinfo.Province:
				if p.Province == "" {
					continue
				}
				_cols = append(_cols, tblusersinfo.Province.Quote())
				_vals = append(_vals, p.Province)
			case tblusersinfo.City:
				if p.City == "" {
					continue
				}
				_cols = append(_cols, tblusersinfo.City.Quote())
				_vals = append(_vals, p.City)
			case tblusersinfo.Utime:
				if p.Utime.IsZero() {
					continue
				}
				_cols = append(_cols, tblusersinfo.Utime.Quote())
				_vals = append(_vals, p.Utime)
			}
		}
		return _cols, _vals
	}

	_cols = make([]string, 0, _lens)
	_vals = make([]any, 0, _lens)
	for _, arg := range args {
		switch arg {
		case tblusersinfo.Id:
			_cols = append(_cols, tblusersinfo.Id.Quote())
			_vals = append(_vals, p.Id)
		case tblusersinfo.Name:
			_cols = append(_cols, tblusersinfo.Name.Quote())
			_vals = append(_vals, p.Name)
		case tblusersinfo.IdNumber:
			_cols = append(_cols, tblusersinfo.IdNumber.Quote())
			_vals = append(_vals, p.IdNumber)
		case tblusersinfo.Country:
			_cols = append(_cols, tblusersinfo.Country.Quote())
			_vals = append(_vals, p.Country)
		case tblusersinfo.Province:
			_cols = append(_cols, tblusersinfo.Province.Quote())
			_vals = append(_vals, p.Province)
		case tblusersinfo.City:
			_cols = append(_cols, tblusersinfo.City.Quote())
			_vals = append(_vals, p.City)
		case tblusersinfo.Utime:
			_cols = append(_cols, tblusersinfo.Utime.Quote())
			_vals = append(_vals, p.Utime)
		}
	}
	return _cols, _vals
}

func (p *UsersInfo) AssignKeys() (dialect.Field, any) {
	return tblusersinfo.PrimaryKey, p.Id
}

func (p *UsersInfo) AssignPrimaryKeyValues(result sql.Result) error {
	return nil
}
