// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tbldocumenttemplate

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

var (
	Id       = dialect.Field{Name: "id", Json: "id", Table: "document_template", Type: "types.BigInt", IsRelation: false}
	Genre    = dialect.Field{Name: "genre", Json: "genre", Table: "document_template", Type: "types.Int8", IsRelation: false}
	Company  = dialect.Field{Name: "company", Json: "company", Table: "document_template", Type: "types.BigInt", IsRelation: false}
	Way      = dialect.Field{Name: "way", Json: "way", Table: "document_template", Type: "types.Int8", IsRelation: false}
	AuthSign = dialect.Field{Name: "auth_sign", Json: "auth_sign", Table: "document_template", Type: "types.Int8", IsRelation: false}
	Title    = dialect.Field{Name: "title", Json: "title", Table: "document_template", Type: "types.String", IsRelation: false}
	Content  = dialect.Field{Name: "content", Json: "content", Table: "document_template", Type: "types.String", IsRelation: false}
	Url      = dialect.Field{Name: "url", Json: "url", Table: "document_template", Type: "types.String", IsRelation: false}
	HasForm  = dialect.Field{Name: "has_form", Json: "has_form", Table: "document_template", Type: "types.Int8", IsRelation: false}
	State    = dialect.Field{Name: "state", Json: "state", Table: "document_template", Type: "types.Int8", IsRelation: false}
	Utime    = dialect.Field{Name: "utime", Json: "utime", Table: "document_template", Type: "types.Time", IsRelation: false}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		Genre,
		Company,
		Way,
		AuthSign,
		Title,
		Content,
		Url,
		HasForm,
		State,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		Id,
		Genre,
		Company,
		Way,
		AuthSign,
		Title,
		Content,
		Url,
		HasForm,
		State,
		Utime,
	}
)
