// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package usertbl

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

var (
	ID          = dialect.Field{Name: "id", Table: "user", Type: "uint64"}
	Name        = dialect.Field{Name: "name", Table: "user", Type: "string"}
	Avatar      = dialect.Field{Name: "avatar", Table: "user", Type: "string"}
	Nickname    = dialect.Field{Name: "nickname", Table: "user", Type: "string"}
	Status      = dialect.Field{Name: "status", Table: "user", Type: "int8"}
	IsAllow     = dialect.Field{Name: "is_allow", Table: "user", Type: "bool"}
	CreatedTime = dialect.Field{Name: "created_time", Table: "user", Type: "time.Time"}
	// 主键
	PrimaryKey = ID

	// 可写列
	WritableFields = []dialect.Field{
		Name,
		Avatar,
		Nickname,
		Status,
		IsAllow,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		ID,
		Name,
		Avatar,
		Nickname,
		Status,
		IsAllow,
		CreatedTime,
	}
)
