// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tblcompanyrule

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

var (
	Id        = dialect.Field{Name: "id", Json: "id", Table: "company_rule", Type: "types.BigInt", IsRelation: false}
	Pid       = dialect.Field{Name: "pid", Json: "pid", Table: "company_rule", Type: "types.BigInt", IsRelation: false}
	Path      = dialect.Field{Name: "path", Json: "path", Table: "company_rule", Type: "types.String", IsRelation: false}
	Title     = dialect.Field{Name: "title", Json: "title", Table: "company_rule", Type: "types.String", IsRelation: false}
	Type      = dialect.Field{Name: "type", Json: "type", Table: "company_rule", Type: "types.Uint8", IsRelation: false}
	IsPrivate = dialect.Field{Name: "is_private", Json: "is_private", Table: "company_rule", Type: "types.Uint8", IsRelation: false}
	State     = dialect.Field{Name: "state", Json: "state", Table: "company_rule", Type: "types.Int8", IsRelation: false}
	Descr     = dialect.Field{Name: "descr", Json: "descr", Table: "company_rule", Type: "types.String", IsRelation: false}
	Belong    = dialect.Field{Name: "belong", Json: "belong", Table: "company_rule", Type: "types.Int8", IsRelation: false}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		Pid,
		Path,
		Title,
		Type,
		IsPrivate,
		State,
		Descr,
		Belong,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		Id,
		Pid,
		Path,
		Title,
		Type,
		IsPrivate,
		State,
		Descr,
		Belong,
	}
)
