// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package dao

import (
	"context"
	"github.com/linbaozhong/gentity/example/model/db"
	"github.com/linbaozhong/gentity/example/model/define/table/companytbl"
	"github.com/linbaozhong/gentity/pkg/ace"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	atype "github.com/linbaozhong/gentity/pkg/ace/types"
)

type CompanyDaoer interface {
	dialect.Daoer
	ace.Cruder
	// InsertOne 插入一条数据，返回 LastInsertId
	// cols: 要插入的列名
	InsertOne(ctx context.Context, bean *db.Company, cols ...dialect.Field) (int64, error)
	// InsertMulti 批量插入多条数据,返回 RowsAffected
	// cols: 要插入的列名
	InsertMulti(ctx context.Context, beans []*db.Company, cols ...dialect.Field) (int64, error)
	// UpdateMulti 批量更新多条数据
	// cols: 要更新的列名
	UpdateMulti(ctx context.Context, beans []*db.Company, cols ...dialect.Field) (bool, error)
	// Find4Cols 分页查询指定列，返回一个slice
	Find4Cols(ctx context.Context, pageIndex, pageSize uint, cols []dialect.Field, cond ...dialect.Condition) ([]*db.Company, bool, error)
	// Find 分页查询，返回一个slice
	Find(ctx context.Context, pageIndex, pageSize uint, cond ...dialect.Condition) ([]*db.Company, bool, error)
	// Get4Cols 读取一个对象的指定列
	Get4Cols(ctx context.Context, cols []dialect.Field, cond ...dialect.Condition) (*db.Company, bool, error)
	// GetByID 按主键查询，返回一个对象
	GetByID(ctx context.Context, args ...any) (*db.Company, bool, error)
	// Get 按条件读取一个对象
	Get(ctx context.Context, cond ...dialect.Condition) (*db.Company, bool, error)
	// GetSingle 按条件读取第一行的第一个字段
	GetSingle(ctx context.Context, col dialect.Field, cond ...dialect.Condition) (any, error)
	//
	IDs(ctx context.Context, cond ...dialect.Condition) ([]int64, error)
	//
	Columns(ctx context.Context, col dialect.Field, cond ...dialect.Condition) ([]any, error)
}

type companyDao struct {
	db ace.Executer
}

func Company(exec ace.Executer) CompanyDaoer {
	return &companyDao{db: exec}
}

// C Create company
func (p *companyDao) C() *ace.Creator {
	return p.db.Insert(db.CompanyTableName)
}

// R Read company
func (p *companyDao) R() *ace.Selector {
	return p.db.Select(db.CompanyTableName)
}

// U Update company
func (p *companyDao) U() *ace.Updater {
	return p.db.Update(db.CompanyTableName)
}

// D Delete company
func (p *companyDao) D() *ace.Deleter {
	return p.db.Delete(db.CompanyTableName)
}

// Insert 返回 LastInsertId
func (p *companyDao) Insert(ctx context.Context, sets ...dialect.Setter) (int64, error) {
	if len(sets) == 0 {
		return 0, atype.ErrSetterEmpty
	}
	result, err := p.C().Set(sets...).Do(ctx)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

// InsertOne 返回 LastInsertId
// cols: 要插入的列名
func (p *companyDao) InsertOne(ctx context.Context, bean *db.Company, cols ...dialect.Field) (int64, error) {
	result, err := p.C().Cols(cols...).Struct(ctx, bean)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

// InsertMulti 批量插入,返回 RowsAffected
// cols: 要插入的列名
func (p *companyDao) InsertMulti(ctx context.Context, beans []*db.Company, cols ...dialect.Field) (int64, error) {
	lens := len(beans)
	if lens == 0 {
		return 0, atype.ErrBeanEmpty
	}
	args := make([]dialect.Modeler, 0, lens)
	for _, bean := range beans {
		args = append(args, bean)
	}
	result, err := p.C().Cols(cols...).Struct(ctx, args...)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

// Update
func (p *companyDao) Update(ctx context.Context, sets []dialect.Setter, cond ...dialect.Condition) (bool, error) {
	if len(sets) == 0 {
		return false, atype.ErrSetterEmpty
	}
	result, err := p.U().Where(cond...).Set(sets...).Do(ctx)
	if err != nil {
		return false, err
	}
	n, err := result.RowsAffected()
	return n >= 0, err
}

// UpdateMulti
// cols: 要更新的列名
func (p *companyDao) UpdateMulti(ctx context.Context, beans []*db.Company, cols ...dialect.Field) (bool, error) {
	lens := len(beans)
	if lens == 0 {
		return false, atype.ErrBeanEmpty
	}
	args := make([]dialect.Modeler, 0, lens)
	for _, bean := range beans {
		args = append(args, bean)
	}
	result, err := p.U().Cols(cols...).Struct(ctx, args...)
	if err != nil {
		return false, err
	}
	n, err := result.RowsAffected()
	return n >= 0, err
}

// Delete
func (p *companyDao) Delete(ctx context.Context, cond ...dialect.Condition) (bool, error) {
	result, err := p.D().Where(cond...).Do(ctx)
	if err != nil {
		return false, err
	}
	n, err := result.RowsAffected()
	return n >= 0, err
}

// Get4Cols
func (p *companyDao) Get4Cols(ctx context.Context, cols []dialect.Field, cond ...dialect.Condition) (*db.Company, bool, error) {
	c := p.R()
	if len(cols) == 0 {
		c.Cols(companytbl.ReadableFields...)
	} else {
		c.Cols(cols...)
	}

	rows, err := c.Where(cond...).Limit(1).Query(ctx)
	if err != nil {
		return nil, false, err
	}
	defer rows.Close()

	obj := db.NewCompany()
	defer obj.Free()

	objs, has, err := obj.Scan(rows, cols...)
	if err != nil {
		return nil, false, err
	}
	if has {
		return objs[0], true, nil
	}

	return nil, false, atype.ErrNotFound
}

// Find4Cols
func (p *companyDao) Find4Cols(ctx context.Context, pageIndex, pageSize uint, cols []dialect.Field, cond ...dialect.Condition) ([]*db.Company, bool, error) {
	c := p.R()
	if len(cols) == 0 {
		c.Cols(companytbl.ReadableFields...)
	} else {
		c.Cols(cols...)
	}
	//
	if pageSize == 0 {
		pageSize = atype.PageSize
	}
	//
	rows, err := c.Where(cond...).Limit(pageSize, pageSize*pageIndex).Query(ctx)
	if err != nil {
		return nil, false, err
	}
	defer rows.Close()

	obj := db.NewCompany()
	defer obj.Free()

	objs, has, err := obj.Scan(rows, cols...)
	if err != nil {
		return nil, false, err
	}
	return objs, has, nil
}

// GetByID Read one company By Primary Key value,
// Pass values in this order：Id
func (p *companyDao) GetByID(ctx context.Context, args ...any) (*db.Company, bool, error) {
	lens := len(companytbl.PrimaryKeys)
	if lens != len(args) {
		return nil, false, atype.ErrArgsNotMatch
	}

	cond := make([]dialect.Condition, 0, lens)
	for i, key := range companytbl.PrimaryKeys {
		cond = append(cond, key.Eq(args[i]))
	}
	return p.Get4Cols(ctx, []dialect.Field{}, cond...)
}

// Get Read one company
func (p *companyDao) Get(ctx context.Context, cond ...dialect.Condition) (*db.Company, bool, error) {
	return p.Get4Cols(ctx, []dialect.Field{}, cond...)
}

// GetSingle Read the first column of the first row
func (p *companyDao) GetSingle(ctx context.Context, col dialect.Field, cond ...dialect.Condition) (any, error) {
	c := p.R().Cols(col)
	rows, err := c.Where(cond...).Limit(atype.MaxLimit).Query(ctx)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var v any
	if rows.Next() {
		if err = rows.Scan(&v); err != nil {
			return nil, err
		}
	}

	return v, rows.Err()
}

// Find
func (p *companyDao) Find(ctx context.Context, pageIndex, pageSize uint, cond ...dialect.Condition) ([]*db.Company, bool, error) {
	return p.Find4Cols(ctx, pageIndex, pageSize, []dialect.Field{}, cond...)
}

// IDs
func (p *companyDao) IDs(ctx context.Context, cond ...dialect.Condition) ([]int64, error) {
	if len(companytbl.PrimaryKeys) == 0 {
		return nil, atype.ErrPrimaryKeyNotMatch
	}
	c := p.R().Cols(companytbl.PrimaryKeys[0])
	rows, err := c.Where(cond...).Limit(atype.MaxLimit).Query(ctx)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	ids := make([]int64, atype.PageSize)
	for rows.Next() {
		var id int64
		if err = rows.Scan(&id); err != nil {
			return nil, err
		}
		ids = append(ids, id)
	}

	return ids, rows.Err()
}

// Columns
func (p *companyDao) Columns(ctx context.Context, col dialect.Field, cond ...dialect.Condition) ([]any, error) {
	c := p.R().Cols(col)
	rows, err := c.Where(cond...).Limit(atype.MaxLimit).Query(ctx)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	cols := make([]any, atype.PageSize)
	for rows.Next() {
		var v any
		if err = rows.Scan(&v); err != nil {
			return nil, err
		}
		cols = append(cols, v)
	}
	return cols, rows.Err()
}

// Count
func (p *companyDao) Count(ctx context.Context, cond ...dialect.Condition) (int64, error) {
	return p.R().Count(ctx, cond...)
}

// Sum
func (p *companyDao) Sum(ctx context.Context, col dialect.Field, cond ...dialect.Condition) (int64, error) {
	return p.R().Sum(ctx, col, cond...)
}

// Exists
func (p *companyDao) Exists(ctx context.Context, cond ...dialect.Condition) (bool, error) {
	if len(companytbl.PrimaryKeys) == 0 {
		return false, atype.ErrPrimaryKeyNotMatch
	}
	c := p.R().Cols(companytbl.PrimaryKeys[0]).Where(cond...).Limit(1)
	rows, err := c.Query(ctx)
	if err != nil {
		return false, err
	}
	defer rows.Close()
	return rows.Next(), rows.Err()
}
