// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package dao

import (
	"context"
	"database/sql"
	"encoding/json"
	"github.com/linbaozhong/gentity/example/model/db"
	"github.com/linbaozhong/gentity/example/model/define/table/usertbl"
	"github.com/linbaozhong/gentity/pkg/ace"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	atype "github.com/linbaozhong/gentity/pkg/ace/types"
	"github.com/linbaozhong/gentity/pkg/cachego"
	"github.com/linbaozhong/gentity/pkg/conv"
)

type UserDaoer interface {
	dialect.Daoer
	ace.Cruder
	// InsertOne 插入一条数据，返回 LastInsertId
	// cols: 要插入的列名
	InsertOne(ctx context.Context, bean *db.User, cols ...dialect.Field) (bool, error)
	// InsertBatch 批量插入多条数据,返回 RowsAffected
	// cols: 要插入的列名
	InsertBatch(ctx context.Context, beans []*db.User, cols ...dialect.Field) (int64, error)
	// UpdateById 按主键更新一条数据
	UpdateById(ctx context.Context, id uint64, sets ...dialect.Setter) (bool, error)
	// UpdateBatch 批量更新多条数据
	// cols: 要更新的列名
	UpdateBatch(ctx context.Context, beans []*db.User, cols ...dialect.Field) (bool, error)
	// DeleteById 按主键删除一条数据
	DeleteById(ctx context.Context, id uint64) (bool, error)
	// Find4Cols 分页查询指定列，返回一个slice
	Find4Cols(ctx context.Context, pageIndex, pageSize uint, cols []dialect.Field, cond ...dialect.Condition) ([]*db.User, bool, error)
	// Find 分页查询，返回一个slice
	Find(ctx context.Context, pageIndex, pageSize uint, cond ...dialect.Condition) ([]*db.User, bool, error)
	// Get4Cols 读取一个对象的指定列
	Get4Cols(ctx context.Context, cols []dialect.Field, cond ...dialect.Condition) (*db.User, bool, error)
	// GetByID 按主键查询，返回一个对象
	GetByID(ctx context.Context, id uint64, cols ...dialect.Field) (*db.User, bool, error)
	// Get 按条件读取一个对象
	Get(ctx context.Context, cond ...dialect.Condition) (*db.User, bool, error)
	// GetFirstCell 按条件读取第一行的第一个字段
	GetFirstCell(ctx context.Context, col dialect.Field, cond ...dialect.Condition) (any, bool, error)
	//
	IDs(ctx context.Context, cond ...dialect.Condition) ([]any, error)
	//
	Columns(ctx context.Context, col dialect.Field, cond ...dialect.Condition) ([]any, error)
}

type userDao struct {
	db    ace.Executer
	cache cachego.Cache
}

func User(exec ace.Executer) UserDaoer {
	return &userDao{db: exec, cache: exec.Cache()}
}

// C Create user
func (p *userDao) C() *ace.Creator {
	return p.db.C(db.UserTableName)
}

// R Read user
func (p *userDao) R() *ace.Selector {
	return p.db.R(db.UserTableName)
}

// U Update user
func (p *userDao) U() *ace.Updater {
	return p.db.U(db.UserTableName)
}

// D Delete user
func (p *userDao) D() *ace.Deleter {
	return p.db.D(db.UserTableName)
}

// Insert 返回 LastInsertId
func (p *userDao) Insert(ctx context.Context, sets ...dialect.Setter) (int64, error) {
	if len(sets) == 0 {
		return 0, atype.ErrSetterEmpty
	}
	result, err := p.C().
		Set(sets...).
		Exec(ctx)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

// InsertOne 返回 LastInsertId
// cols: 要插入的列名
func (p *userDao) InsertOne(ctx context.Context, bean *db.User, cols ...dialect.Field) (bool, error) {
	result, err := p.C().
		Cols(cols...).
		Struct(ctx, bean)
	if err != nil {
		return false, err
	}

	bean.AssignPrimaryKeyValues(result)

	n, err := result.RowsAffected()
	return n > 0, err
}

// InsertBatch 批量插入,返回 RowsAffected
// cols: 要插入的列名
func (p *userDao) InsertBatch(ctx context.Context, beans []*db.User, cols ...dialect.Field) (int64, error) {
	lens := len(beans)
	if lens == 0 {
		return 0, atype.ErrBeanEmpty
	}
	args := make([]dialect.Modeler, 0, lens)
	for _, bean := range beans {
		args = append(args, bean)
	}
	result, err := p.C().
		Cols(cols...).
		Struct(ctx, args...)
	if err != nil {
		return 0, err
	}

	return result.RowsAffected()
}

// Update
func (p *userDao) Update(ctx context.Context, sets []dialect.Setter, cond ...dialect.Condition) (bool, error) {
	if len(sets) == 0 {
		return false, atype.ErrSetterEmpty
	}
	result, err := p.U().
		Where(cond...).
		Set(sets...).
		Exec(ctx)
	if err != nil {
		return false, err
	}
	n, err := result.RowsAffected()
	return n >= 0, err
}

// UpdateById
func (p *userDao) UpdateById(ctx context.Context, id uint64, sets ...dialect.Setter) (bool, error) {
	return p.Update(ctx,
		sets,
		usertbl.ID.Eq(id),
	)
}

// UpdateBatch
// cols: 要更新的列名
func (p *userDao) UpdateBatch(ctx context.Context, beans []*db.User, cols ...dialect.Field) (bool, error) {
	lens := len(beans)
	if lens == 0 {
		return false, atype.ErrBeanEmpty
	}
	args := make([]dialect.Modeler, 0, lens)
	for _, bean := range beans {
		args = append(args, bean)
	}
	result, err := p.U().
		Cols(cols...).
		Struct(ctx, args...)
	if err != nil {
		return false, err
	}
	n, err := result.RowsAffected()
	return n >= 0, err
}

// Delete
func (p *userDao) Delete(ctx context.Context, cond ...dialect.Condition) (bool, error) {
	result, err := p.D().
		Where(cond...).
		Exec(ctx)
	if err != nil {
		return false, err
	}
	n, err := result.RowsAffected()
	return n >= 0, err
}

// DeleteById
func (p *userDao) DeleteById(ctx context.Context, id uint64) (bool, error) {
	return p.Delete(ctx,
		usertbl.ID.Eq(id),
	)
}

// Get4Cols
func (p *userDao) Get4Cols(ctx context.Context, cols []dialect.Field, cond ...dialect.Condition) (*db.User, bool, error) {
	c := p.R()
	if len(cols) == 0 {
		c.Cols(usertbl.ReadableFields...)
	} else {
		c.Cols(cols...)
	}

	row, err := c.Where(cond...).
		QueryRow(ctx)
	if err != nil {
		return nil, false, err
	}

	obj := db.NewUser()
	defer obj.Free()

	err = row.Scan(obj.AssignPtr(cols...)...)
	switch err {
	case sql.ErrNoRows:
		return nil, false, nil
	case nil:
		return obj, true, nil
	default:
		return nil, false, err
	}
}

// Find4Cols
func (p *userDao) Find4Cols(ctx context.Context, pageIndex, pageSize uint, cols []dialect.Field, cond ...dialect.Condition) ([]*db.User, bool, error) {
	c := p.R()
	if len(cols) == 0 {
		c.Cols(usertbl.ReadableFields...)
	} else {
		c.Cols(cols...)
	}
	//
	if pageSize == 0 {
		pageSize = atype.PageSize
	}
	//
	rows, err := c.Where(cond...).
		Limit(pageSize, pageSize*pageIndex).
		Query(ctx)
	if err != nil {
		return nil, false, err
	}
	defer rows.Close()

	obj := db.NewUser()
	defer obj.Free()

	objs, has, err := obj.Scan(rows, cols...)
	if err != nil {
		return nil, false, err
	}
	return objs, has, nil
}

// GetByID Read one user By Primary Key value,
func (p *userDao) GetByID(ctx context.Context, id uint64, cols ...dialect.Field) (*db.User, bool, error) {
	return p.Get4Cols(ctx, cols, usertbl.ID.Eq(id))
}

// Get Read one user
func (p *userDao) Get(ctx context.Context, cond ...dialect.Condition) (*db.User, bool, error) {
	return p.Get4Cols(ctx, []dialect.Field{}, cond...)
}

// GetFirstCell Read the first column of the first row
func (p *userDao) GetFirstCell(ctx context.Context, col dialect.Field, cond ...dialect.Condition) (any, bool, error) {
	c := p.R().Cols(col)
	row, err := c.Where(cond...).QueryRow(ctx)
	if err != nil {
		return nil, false, err
	}

	var v any
	err = row.Scan(&v)
	switch err {
	case sql.ErrNoRows:
		return nil, false, nil
	case nil:
		return v, true, nil
	default:
		return nil, false, err
	}
}

// Find
func (p *userDao) Find(ctx context.Context, pageIndex, pageSize uint, cond ...dialect.Condition) ([]*db.User, bool, error) {
	return p.Find4Cols(ctx, pageIndex, pageSize, []dialect.Field{}, cond...)
}

// IDs
func (p *userDao) IDs(ctx context.Context, cond ...dialect.Condition) ([]any, error) {
	c := p.R().Cols(usertbl.ID)
	rows, err := c.Where(cond...).
		Limit(atype.MaxLimit).
		Query(ctx)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	ids := make([]any, 0, atype.PageSize)
	for rows.Next() {
		var id uint64
		if err = rows.Scan(&id); err != nil {
			return nil, err
		}
		ids = append(ids, id)
	}

	return ids, rows.Err()
}

// Columns
func (p *userDao) Columns(ctx context.Context, col dialect.Field, cond ...dialect.Condition) ([]any, error) {
	c := p.R().Cols(col)
	rows, err := c.Where(cond...).
		Limit(atype.MaxLimit).
		Query(ctx)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	cols := make([]any, 0, atype.PageSize)
	for rows.Next() {
		var v any
		if err = rows.Scan(&v); err != nil {
			return nil, err
		}
		cols = append(cols, v)
	}
	return cols, rows.Err()
}

// Count
func (p *userDao) Count(ctx context.Context, cond ...dialect.Condition) (int64, error) {
	return p.R().Count(ctx, cond...)
}

// Sum
func (p *userDao) Sum(ctx context.Context, col dialect.Field, cond ...dialect.Condition) (int64, error) {
	return p.R().Sum(ctx, col, cond...)
}

// Exists
func (p *userDao) Exists(ctx context.Context, cond ...dialect.Condition) (bool, error) {
	c := p.R().Cols(usertbl.ID).Where(cond...)
	row, err := c.QueryRow(ctx)
	if err != nil {
		return false, err
	}

	var id uint64
	err = row.Scan(&id)
	switch err {
	case sql.ErrNoRows:
		return false, nil
	case nil:
		return true, nil
	default:
		return false, err
	}
}

// onUpdate
func (p *userDao) onUpdate(ctx context.Context, ids ...uint64) error {
	for _, id := range ids {
		if err := p.cache.Delete(ctx, db.UserTableName+":id:"+conv.Interface2String(id)); err != nil {
			return err
		}
	}

	return p.cache.Delete(ctx, db.UserTableName+":ids")
}

// getCache
func (p *userDao) getCache(ctx context.Context, id uint64) (*db.User, bool, error) {
	s, err := p.cache.Fetch(ctx, db.UserTableName+":id:"+conv.Interface2String(id))
	if err != nil {
		return nil, false, err
	}
	if len(s) == 0 {
		return nil, false, nil
	}
	obj := db.NewUser()
	err = json.Unmarshal(s, obj)
	if err != nil {
		return nil, false, err
	}
	return obj, true, nil
}

// setCache
func (p *userDao) setCache(ctx context.Context, obj *db.User) error {
	s, err := json.Marshal(obj)
	if err != nil {
		return err
	}
	return p.cache.Save(ctx, db.UserTableName+":id:"+conv.Interface2String(obj.ID), string(s), 0)
}
