// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tbluser

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

const TableName = "user"

var (
	Id       = dialect.Field{Name: "id", Json: "id", Table: "user", Type: "types.BigInt", IsRelation: false}
	Name     = dialect.Field{Name: "name", Json: "name", Table: "user", Type: "types.String", IsRelation: false}
	Email    = dialect.Field{Name: "email", Json: "email", Table: "user", Type: "types.String", IsRelation: false}
	Mobile   = dialect.Field{Name: "mobile", Json: "mobile", Table: "user", Type: "types.String", IsRelation: false}
	Gender   = dialect.Field{Name: "gender", Json: "gender", Table: "user", Type: "types.String", IsRelation: false}
	Birthday = dialect.Field{Name: "birthday", Json: "birthday", Table: "user", Type: "types.String", IsRelation: false}
	Creator  = dialect.Field{Name: "creator", Json: "creator", Table: "user", Type: "types.BigInt", IsRelation: false}
	Status   = dialect.Field{Name: "status", Json: "status", Table: "user", Type: "types.Int8", IsRelation: false}
	State    = dialect.Field{Name: "state", Json: "state", Table: "user", Type: "types.Int8", IsRelation: false}
	Ctime    = dialect.Field{Name: "ctime", Json: "ctime", Table: "user", Type: "types.Time", IsRelation: false}
	Utime    = dialect.Field{Name: "utime", Json: "utime", Table: "user", Type: "types.Time", IsRelation: false}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		Id,
		Name,
		Email,
		Mobile,
		Gender,
		Birthday,
		Creator,
		Status,
		State,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		Id,
		Name,
		Email,
		Mobile,
		Gender,
		Birthday,
		Creator,
		Status,
		State,
		Ctime,
		Utime,
	}
)
