// Copyright © 2023 Linbaozhong. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package schema

import (
	"bytes"
	"fmt"
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
	"github.com/linbaozhong/gentity/pkg/sqlparser"
	"io"
	"os"
	"sort"
	"strings"
)

func Sql2Struct(buf []byte, packageName string) ([]byte, error) {
	return reader2Struct(bytes.NewReader(buf), packageName)
}

func SqlFile2Struct(filePath, packageName string) ([]byte, error) {
	_f, e := os.Open(filePath)
	if e != nil {
		return nil, e
	}
	defer _f.Close()

	return reader2Struct(_f, packageName)
}

func reader2Struct(r io.Reader, packageName string) ([]byte, error) {
	_parser := sqlparser.NewParser(r)
	_schema, e := _parser.Parse()
	if e != nil {
		return nil, e
	}

	var buf bytes.Buffer
	// buf.WriteString("// Code generated by gentity. DO NOT EDIT.\n\n")
	buf.WriteString("package " + packageName + "\n\n")
	buf.WriteString("import (\n")
	// buf.WriteString("	\"time\" \n")
	buf.WriteString("	\"github.com/linbaozhong/gentity/pkg/ace/pool\" \n")
	buf.WriteString("	\"github.com/linbaozhong/gentity/pkg/types\" \n")
	// buf.WriteString("	\"sync/atomic\" \n")
	buf.WriteString(") \n\n")
	//

	for _, table := range _schema {
		buf.WriteString("// " + ParseField(table.Name) + " " + table.Extras["COMMENT"] + "\n")
		buf.WriteString("// @tablename " + table.Name + "\n")
		// buf.WriteString("// cache time.Minute time.Minute 1000 \n")
		buf.WriteString("type " + ParseField(table.Name) + " struct {\n")
		buf.WriteString("\tpool.Model\n")
		//
		parseColumnType(table.ColumnsX)
		//
		for _, col := range table.ColumnsX {
			buf.WriteString("\t" + ParseField(col.Name) + "\t" + col.Type)
			buf.WriteString("\t`json:\"" + col.Name + ",omitempty\" db:\"'" + col.Name + "'") //
			if strings.ToUpper(col.Key) == dialect.PrimaryKey {
				buf.WriteString(" pk")
			}
			if col.AutoIncr {
				buf.WriteString(" auto")
			}
			if v, ok := col.Default.(string); ok && len(v) > 0 {
				if strings.HasPrefix(v, "current_timestamp") {
					buf.WriteString(" <-")
				}
			}

			buf.WriteString(ParseFieldSize(col))
			buf.WriteString(fmt.Sprintf("\"`	// %s\n", strings.TrimSpace(col.Comment)))
		}
		buf.WriteString("} \n\n")
	}
	return buf.Bytes(), nil
}

func DB2Struct(tables []*sqlparser.Table, packageName string) ([]byte, error) {
	var buf bytes.Buffer
	// buf.WriteString("// Code generated by gentity. DO NOT EDIT.\n\n")
	buf.WriteString("package " + packageName + "\n\n")
	buf.WriteString("import (\n")
	// buf.WriteString("	\"time\" \n")
	buf.WriteString("	\"github.com/linbaozhong/gentity/pkg/ace/pool\" \n")
	buf.WriteString("	\"github.com/linbaozhong/gentity/pkg/types\" \n")
	// buf.WriteString("	\"sync/atomic\" \n")
	buf.WriteString(") \n\n")

	for _, table := range tables {
		buf.WriteString("// " + ParseField(table.Name) + " " + table.Comment + "\n")
		buf.WriteString("// @tablename " + table.Name + "\n")
		// buf.WriteString("// cache time.Minute time.Minute 1000 \n")
		buf.WriteString("type " + ParseField(table.Name) + " struct {\n")
		buf.WriteString("\tpool.Model\n")
		//
		// for i := 0; i < len(table.ColumnsX); i++ {
		// 	typeName := ParseFieldAceType(table.ColumnsX[i])
		// 	table.ColumnsX[i].Type = typeName
		// 	table.ColumnsX[i].Info = sqlparser.GetTypeInfo(typeName)
		// 	table.ColumnsX[i].Index = i
		// }
		// sort.SliceStable(table.ColumnsX, func(i, j int) bool {
		// 	if table.ColumnsX[i].Info.Align != table.ColumnsX[j].Info.Align {
		// 		return table.ColumnsX[i].Info.Align > table.ColumnsX[j].Info.Align
		// 	}
		// 	if table.ColumnsX[i].Info.Size != table.ColumnsX[j].Info.Size {
		// 		return table.ColumnsX[i].Info.Size > table.ColumnsX[j].Info.Size
		// 	}
		// 	return table.ColumnsX[i].Index < table.ColumnsX[j].Index
		// })
		parseColumnType(table.ColumnsX)
		//
		for _, col := range table.ColumnsX {
			buf.WriteString("\t" + ParseField(col.Name) + "\t" + col.Type)
			buf.WriteString("\t`json:\"" + col.Name + ",omitempty\" db:\"'" + col.Name + "'") //
			if strings.ToUpper(col.Key) == dialect.PrimaryKey {
				buf.WriteString(" pk")
			}
			if col.AutoIncr {
				buf.WriteString(" auto")
			}
			if strings.HasPrefix(col.Extra, "DEFAULT_GENERATED") {
				buf.WriteString(" <-")
			}
			buf.WriteString(ParseFieldSize(col))
			buf.WriteString(fmt.Sprintf("\"`	// %s\n", strings.ReplaceAll(col.Comment, "\n", "")))
		}
		buf.WriteString("} \n\n")
	}
	return buf.Bytes(), nil
}

func parseColumnType(cols []*sqlparser.Column) {
	//
	for i := 0; i < len(cols); i++ {
		typeName := ParseFieldAceType(cols[i])
		cols[i].Type = typeName
		cols[i].Info = sqlparser.GetTypeInfo(typeName)
		cols[i].Index = i
	}
	sort.SliceStable(cols, func(i, j int) bool {
		if cols[i].Info.Align != cols[j].Info.Align {
			return cols[i].Info.Align > cols[j].Info.Align
		}
		if cols[i].Info.Size != cols[j].Info.Size {
			return cols[i].Info.Size > cols[j].Info.Size
		}
		return cols[i].Index < cols[j].Index
	})

}
