// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tbluser

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

var (
	Id       = dialect.Field{Name: "id", Json: "id", Table: "user", Type: "types.BigInt"}
	Uuid     = dialect.Field{Name: "uuid", Json: "uuid", Table: "user", Type: "types.String"}
	Ctime    = dialect.Field{Name: "ctime", Json: "ctime", Table: "user", Type: "types.Time"}
	UserLogs = dialect.Field{Name: "user_logs", Json: "user_logs", Table: "user", Type: "[]UserLog"}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		Uuid,
		Ctime,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		Id,
		Uuid,
		Ctime,
	}
)
