// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tblcompanyrole

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

var (
	Id        = dialect.Field{Name: "id", Json: "id", Table: "company_role", Type: "types.BigInt"}
	CompanyId = dialect.Field{Name: "company_id", Json: "company_id", Table: "company_role", Type: "types.BigInt"}
	Name      = dialect.Field{Name: "name", Json: "name", Table: "company_role", Type: "types.String"}
	Descr     = dialect.Field{Name: "descr", Json: "descr", Table: "company_role", Type: "types.String"}
	Rules     = dialect.Field{Name: "rules", Json: "rules", Table: "company_role", Type: "types.String"}
	Type      = dialect.Field{Name: "type", Json: "type", Table: "company_role", Type: "types.Int8"}
	State     = dialect.Field{Name: "state", Json: "state", Table: "company_role", Type: "types.Int8"}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		CompanyId,
		Name,
		Descr,
		Rules,
		Type,
		State,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		Id,
		CompanyId,
		Name,
		Descr,
		Rules,
		Type,
		State,
	}
)
