// Code generated by github.com/linbaozhong/gentity. DO NOT EDIT.

package tblusers

import (
	"github.com/linbaozhong/gentity/pkg/ace/dialect"
)

var (
	Id         = dialect.Field{Name: "id", Json: "id", Table: "users", Type: "types.BigInt"}
	From       = dialect.Field{Name: "from", Json: "from", Table: "users", Type: "types.String"}
	OpenId     = dialect.Field{Name: "open_id", Json: "open_id", Table: "users", Type: "types.String"}
	UnionId    = dialect.Field{Name: "union_id", Json: "union_id", Table: "users", Type: "types.String"}
	SessionKey = dialect.Field{Name: "session_key", Json: "session_key", Table: "users", Type: "types.String"}
	Mobile     = dialect.Field{Name: "mobile", Json: "mobile", Table: "users", Type: "types.String"}
	Email      = dialect.Field{Name: "email", Json: "email", Table: "users", Type: "types.String"}
	Pwd        = dialect.Field{Name: "pwd", Json: "pwd", Table: "users", Type: "types.String"}
	Avatar     = dialect.Field{Name: "avatar", Json: "avatar", Table: "users", Type: "types.String"}
	Nick       = dialect.Field{Name: "nick", Json: "nick", Table: "users", Type: "types.String"}
	Gender     = dialect.Field{Name: "gender", Json: "gender", Table: "users", Type: "types.String"}
	State      = dialect.Field{Name: "state", Json: "state", Table: "users", Type: "types.Int8"}
	Ctime      = dialect.Field{Name: "ctime", Json: "ctime", Table: "users", Type: "types.Time"}
	// 主键
	PrimaryKey = Id

	// 可写列
	WritableFields = []dialect.Field{
		Id,
		From,
		OpenId,
		UnionId,
		SessionKey,
		Mobile,
		Email,
		Pwd,
		Avatar,
		Nick,
		Gender,
		State,
		Ctime,
	}
	// 可读列
	ReadableFields = []dialect.Field{
		Id,
		From,
		OpenId,
		UnionId,
		SessionKey,
		Mobile,
		Email,
		Pwd,
		Avatar,
		Nick,
		Gender,
		State,
		Ctime,
	}
)
